import random
from sklearn.tree import DecisionTreeClassifier;
import pandas as pd;
import math
import json
import pprint;
from collections import deque

indice_sequenciaDeAcoes = 0
sequenciaDeAcoes = []

ACOES = ["bomba", "atacar, fugir, afastar, aproximar, pegar"]
DIRECAO = ["cima", "baixo", "esquerda", "direita", "parado"]

    





def arvoreDeDecisoes(TrainningData):
    X_treino = TrainningData.drop(columns=['funcao'])
    Y_treino = TrainningData['funcao']
    
    model = DecisionTreeClassifier()
    
    model.fit(X_treino, Y_treino)
    
    return model

def arvorePredict(realData, trainningData):
    model = arvoreDeDecisoes(trainningData)
    result = model.predict(realData)
    print("\n\n arvorePredict \n\n")
    print(result)
    try:
        return result
    except Exception:
        return result


def gerar_dados_treinamento(
    qtd_exemplos=30,
    funcao="fugir",
    perigo=1,
    oportunidade=0,
    neutro=0,
    player_index=1,
    limite_distancia=12,          
    distancia_perto=5,
    limite_powerup=12,
    bomba_existe=1,
    bomba_player=1,
    limite_min_distancia=1,
    limite_min_powerup=1
):
    """
    Gera dados sintéticos controlados apenas com distâncias, para treinar IA.

    - `limite_distancia`: distância máxima possível de geração aleatória.
    - `distancia_perto`: distância usada para marcar se há jogadores próximos.
    """

    if player_index not in [1, 2, 3, 4]:
        raise ValueError("player_index deve ser um número entre 1 e 4.")

    dados = []

    for _ in range(qtd_exemplos):
        # --- DISTÂNCIAS DOS JOGADORES ---
        dist_jogadores = {}
        jogadores_perto = 0

        for i in range(1, 5):
            if i == player_index:
                dist_jogadores[i] = 0
                continue

            if perigo:
                min_val = limite_min_distancia
                max_val = limite_distancia
            else:
                min_val = limite_distancia + 1
                max_val = limite_distancia * 2

            dist = random.randint(min_val, max_val)
            dist_jogadores[i] = dist

            # Agora usa o novo parâmetro para verificar proximidade
            if dist <= distancia_perto:
                jogadores_perto += 1

        mais_de_um_jogador_perto = 1 if jogadores_perto > 1 else 0

        # --- DISTÂNCIAS DAS BOMBAS ---
        dist_bombas = {}

        if bomba_existe:
            for i in range(1, 5):
                if i == player_index:
                    if bomba_player == 1:
                        min_b = limite_min_distancia
                        max_b = min(3, limite_distancia)
                        max_b = max(min_b, max_b)
                        dist_bombas[i] = random.randint(min_b, max_b)
                    else:
                        dist_bombas[i] = 0
                else:
                    dist_jog = dist_jogadores[i]
                    max_v = limite_distancia * 2
                    min_v = limite_min_distancia

                    nova_dist = dist_jog + random.randint(-2, 2)
                    nova_dist = max(min_v, min(nova_dist, max_v))
                    dist_bombas[i] = nova_dist
        else:
            for i in range(1, 5):
                dist_bombas[i] = 0

        # --- POWERUP ---
        powerup_existe = random.choice([0, 1])
        if powerup_existe:
            min_pu = limite_min_powerup
            max_pu = limite_powerup
            max_pu = max(min_pu, max_pu)
            dist_powerup = random.randint(min_pu, max_pu)
        else:
            dist_powerup = 0

        player_com_powerup = random.choice([0, 1])

        linha = {
            "dist_jogador1": dist_jogadores[1],
            "dist_jogador2": dist_jogadores[2],
            "dist_jogador3": dist_jogadores[3],
            "dist_jogador4": dist_jogadores[4],
            "dist_bomba1": dist_bombas[1],
            "dist_bomba2": dist_bombas[2],
            "dist_bomba3": dist_bombas[3],
            "dist_bomba4": dist_bombas[4],
            "bomba_player": bomba_player,
            "bomba_existe": bomba_existe,
            "powerup_existe": powerup_existe,
            "dist_powerup": dist_powerup,
            "player_com_powerup": player_com_powerup,
            "perigo": perigo,
            "mais_de_um_jogador_perto": mais_de_um_jogador_perto,
            "oportunidade": oportunidade,
            "neutro": neutro,
            "funcao": funcao
        }

        dados.append(linha)

    print("\n--- Dados gerados com sucesso ✅ ---\n")
    return dados



    


def gerar_dado_real(qtd_exemplos=1):
    dados = []

    for _ in range(qtd_exemplos):
        # Posições no mapa (13x11)
        player_x, player_y = random.randint(0, 12), random.randint(0, 10)
        inimigo_x, inimigo_y = random.randint(0, 12), random.randint(0, 10)
        bomba_x, bomba_y = random.randint(0, 12), random.randint(0, 10)

        # Distâncias
        distancia_inimigo = round(math.dist([player_x, player_y], [inimigo_x, inimigo_y]), 2)
        distancia_bomba = round(math.dist([player_x, player_y], [bomba_x, bomba_y]), 2)

        # Outros fatores do ambiente
        num_bombas_ativas = random.randint(0, 5)
        tempo_restante = random.randint(0, 300)
        pontos = random.randint(0, 1000)
        hud_info = random.randint(0, 3)
        self_state = random.randint(0, 5)


        # Monta uma linha
        dados.append({
            "player_x": player_x,
            "player_y": player_y,
            "inimigo_x": inimigo_x,
            "inimigo_y": inimigo_y,
            "bomba_x": bomba_x,
            "bomba_y": bomba_y,
            "distancia_inimigo": distancia_inimigo,
            "distancia_bomba": distancia_bomba,
            "num_bombas_ativas": num_bombas_ativas,
            "tempo_restante": tempo_restante,
            "pontos": pontos,
            "hud_info": hud_info,
            "self_state": self_state
        })
    dataframe = pd.DataFrame(dados)
    print("\n\ngerar_Dado_Real \n\n")
    print(dataframe)
    return dataframe
    
# dadoReal = gerar_dado_real()

# arvorePredict(dadoReal)

def log_estado_jogo(player, jogadores, bombas, mapa):
    print("\n========== ESTADO ATUAL DO JOGO ==========")

    print("\n🧍 JOGADORES:")
    for i, j in enumerate(jogadores, start=1):
        print(
            f"Jogador {i}: ativo={j.ativo}, tipo={j.tipo}, time={j.time}, "
            f"pos=({j.grid_x},{j.grid_y}), bombas={len(j.bombas)}, nivel={j.bomba_nivel}"
        )

    print(f"\n⭐ JOGADOR PRINCIPAL:")
    print(
        f"pos=({player.grid_x},{player.grid_y}), ativo={player.ativo}, "
        f"tipo={player.tipo}, time={player.time}, bombas={len(player.bombas)}, nivel={player.bomba_nivel}"
    )

    print("\n💣 BOMBAS:")
    if not bombas:
        print("Nenhuma bomba ativa.")
    else:
        for i, b in enumerate(bombas, start=1):
            try:
                dono_id = jogadores.index(b.dono) + 1
            except ValueError:
                dono_id = "?"
            print(
                f"Bomba {i}: pos=({b.x},{b.y}), explodida={b.explodida}, "
                f"dono=Jogador {dono_id}, fogo={len(b.fogo)} tiles"
            )

    print("\n🔹 POWERUPS NO MAPA:")
    powerups = []
    for y, linha in enumerate(mapa):
        for x, val in enumerate(linha):
            if val in [3, 4]:
                tipo = "BOMBA" if val == 3 else "FOGO"
                powerups.append((x, y, tipo))
    if not powerups:
        print("Nenhum power-up ativo.")
    else:
        for (x, y, tipo) in powerups:
            print(f"PowerUp {tipo} em ({x},{y})")

    print("==========================================\n")

    
    
def distancia_manhattan(x1, y1, x2, y2):
    return abs(x1 - x2) + abs(y1 - y2)




    
def filtrarDadosTreinamento(dadosDeTreinamento, **filtros):
    """
    Filtra dados de treinamento (lista de dicionários) com base em condições dinâmicas.

    Exemplo:
        filtrados = filtrarDadosTreinamento(dados, perigo=1, funcao="fugir")

    - Retorna apenas os registros que satisfazem TODAS as condições fornecidas.
    - Ignora filtros que não existem no dicionário.
    """
    if not isinstance(dadosDeTreinamento, list):
        raise ValueError("dadosDeTreinamento deve ser uma lista de dicionários")

    if not filtros:
        return dadosDeTreinamento  # sem filtros → retorna tudo

    filtrados = []
    for item in dadosDeTreinamento:
        # verifica se o item atende a todos os filtros
        if all(str(item.get(chave)) == str(valor) for chave, valor in filtros.items()):
            filtrados.append(item)

    return filtrados




# dadosTreinamento = gerar_dados_treinamento(
#     qtd_exemplos=50,
#     funcao="passear_pelo_mapa",
#     perigo=0,
#     oportunidade=0,
#     neutro=1,
#     player_index=1,
#     limite_distancia=12,
#     distancia_perto=5,   
#     limite_powerup=12,
#     bomba_existe=0,
#     bomba_player=0,
#     limite_min_distancia=6,
#     limite_min_powerup=1
# )
#Incrementos nos dados:
#Caso bomba esteja a uma distancia X, fugir ou atacar e desviar

#Dados já gerados:
#Caso Perigo=1 e +1JogadoresPerto=1 -> fugir
#Caso Perigo=1 e +1JogadoresPerto=0 -> atacar_e_desviar
#Caso Oportunidade=1 e powerup_existe=1 -> 


    

    
    
    
    
    
    
    
    
    
    
    
    
    
# Parâmetros de jogo
# TILE_SIZE = 48
# ROWS, COLS = 11, 13
# HUD_HEIGHT = 60
# WIDTH, HEIGHT = COLS * TILE_SIZE, ROWS * TILE_SIZE
# TEMPO_MOVIMENTO = 0.1
# TEMPO_EXPLOSAO = 4
# TEMPO_FOGO = 0.5
# MAX_BOMBAS = 5
# TEMPO_PARTIDA = 180

# PONTOS_BLOCO = 100
# PONTOS_POWERUP_COLETADO = 200
# PONTOS_POWERUP_DESTRUIDO = -50
# PONTOS_MATAR_JOGADOR = 1000
# PONTOS_VITORIA = 10000

# PROB_BOMBA = 0.12
# PROB_FOGO = 0.10


# Funções de camada inferior não executam outras funções dentro dela
# Funções de camada intermediario executam funções de camada inferior
# Funções de camada superior executam funções de camada intermediária e inferior

# A função da camada superior deve juntar e/ou retornar um array das ações planejadas pela IA que será armazenado em sequenciaDeAcoes
# O decidir_acao só pode retornar 1 string/ação por vez. Isso será controlado por indice_sequenciaDeAcoes, que será resetado quando uma nova sequenciaDeAcoes for definida
# A sequencia de Ações irá persistir até que uma situação nova aconteça.
# O contexto ou estado do jogo será armazenado, sendo atualizado a cada frame por X frames. Ao ser identificado uma situação nova(como perigo, oportunidade ou a mudança do estado de algo que tava na sequencia de ações, tipo um jogador morre ou parede alvo quebra) a sequencia de ações então será reexecutada

# Colocar a arvore de decisões do SCKIT-LEARN para tomar decisões gerais(quebrar paredes? atacar jogadores? pegar powerUp?). A arvore irá receber dataFrame(podemos usar o pandas) e será treinada com esse dataFrame, com base nos diferentes contextos que a gente por no dataFrame a IA vai analisar e tomar uma decisão do que fazer...

# exemplo: 
# dist_jogador	explosao_perto	bloqueado	ação
#     1	               1	        0	    fugir
#     2	               0	        1	    colocar_bomba
#     5	               0	        0	    andar

# A IA é treinada com um dataFrame assim e então quando dermos uma nova situação, ela consegue prever qual ação tomar

# Dentro das funções utilizamos Node, DecisionNode ou SequencialNode para controlar o comportamento

#FUNÇÕES DE PESQUISA
# def localizacaoJogador():
# def localizacaoPowerUp():
# def localizacaoParedes():
# def caminho():
# def localizacaoBombas():

# FUNÇÕES DE CAMADA INFERIOR
# def andar(quantidade, direcao):
# def bomba(acao):

# FUNÇÕES DE CAMADA INTERMEDIARIA
# def sairAlcance_bomba():
# def distancia_jogadorEnemy(player[rol, col], enemy[rol, col], mapa)
# def 

# FUNÇÕES DE CAMADA SUPERIOR
# def quebrarParedes():
# def atacarJogador():
# def

def dados_treinamento_fixos():
    return [
  {'bomba_existe': 1,
  'bomba_player': 1,
  'dist_bomba1': 1,
  'dist_bomba2': 3,
  'dist_bomba3': 2,
  'dist_bomba4': 4,
  'dist_jogador1': 0,
  'dist_jogador2': 2,
  'dist_jogador3': 4,
  'dist_jogador4': 6,
  'dist_powerup': 6,
  'funcao': 'fugir',
  'mais_de_um_jogador_perto': 1,
  'neutro': 0,
  'oportunidade': 0,
  'perigo': 1,
  'player_com_powerup': 0,
  'powerup_existe': 1},
 {'bomba_existe': 1,
  'bomba_player': 1,
  'dist_bomba1': 1,
  'dist_bomba2': 5,
  'dist_bomba3': 6,
  'dist_bomba4': 5,
  'dist_jogador1': 0,
  'dist_jogador2': 7,
  'dist_jogador3': 5,
  'dist_jogador4': 5,
  'dist_powerup': 9,
  'funcao': 'fugir',
  'mais_de_um_jogador_perto': 1,
  'neutro': 0,
  'oportunidade': 0,
  'perigo': 1,
  'player_com_powerup': 1,
  'powerup_existe': 1},
 {'bomba_existe': 1,
  'bomba_player': 1,
  'dist_bomba1': 3,
  'dist_bomba2': 3,
  'dist_bomba3': 1,
  'dist_bomba4': 3,
  'dist_jogador1': 0,
  'dist_jogador2': 5,
  'dist_jogador3': 1,
  'dist_jogador4': 2,
  'dist_powerup': 4,
  'funcao': 'fugir',
  'mais_de_um_jogador_perto': 1,
  'neutro': 0,
  'oportunidade': 0,
  'perigo': 1,
  'player_com_powerup': 0,
  'powerup_existe': 1},
 {'bomba_existe': 1,
  'bomba_player': 1,
  'dist_bomba1': 2,
  'dist_bomba2': 2,
  'dist_bomba3': 7,
  'dist_bomba4': 2,
  'dist_jogador1': 0,
  'dist_jogador2': 2,
  'dist_jogador3': 7,
  'dist_jogador4': 2,
  'dist_powerup': 0,
  'funcao': 'fugir',
  'mais_de_um_jogador_perto': 1,
  'neutro': 0,
  'oportunidade': 0,
  'perigo': 1,
  'player_com_powerup': 1,
  'powerup_existe': 0},
 {'bomba_existe': 1,
  'bomba_player': 1,
  'dist_bomba1': 1,
  'dist_bomba2': 4,
  'dist_bomba3': 1,
  'dist_bomba4': 5,
  'dist_jogador1': 0,
  'dist_jogador2': 5,
  'dist_jogador3': 3,
  'dist_jogador4': 5,
  'dist_powerup': 12,
  'funcao': 'fugir',
  'mais_de_um_jogador_perto': 1,
  'neutro': 0,
  'oportunidade': 0,
  'perigo': 1,
  'player_com_powerup': 1,
  'powerup_existe': 1},
 {'bomba_existe': 1,
  'bomba_player': 1,
  'dist_bomba1': 1,
  'dist_bomba2': 2,
  'dist_bomba3': 1,
  'dist_bomba4': 4,
  'dist_jogador1': 0,
  'dist_jogador2': 4,
  'dist_jogador3': 1,
  'dist_jogador4': 4,
  'dist_powerup': 3,
  'funcao': 'fugir',
  'mais_de_um_jogador_perto': 1,
  'neutro': 0,
  'oportunidade': 0,
  'perigo': 1,
  'player_com_powerup': 0,
  'powerup_existe': 1},
 {'bomba_existe': 1,
  'bomba_player': 1,
  'dist_bomba1': 1,
  'dist_bomba2': 11,
  'dist_bomba3': 7,
  'dist_bomba4': 1,
  'dist_jogador1': 0,
  'dist_jogador2': 9,
  'dist_jogador3': 5,
  'dist_jogador4': 3,
  'dist_powerup': 2,
  'funcao': 'fugir',
  'mais_de_um_jogador_perto': 1,
  'neutro': 0,
  'oportunidade': 0,
  'perigo': 1,
  'player_com_powerup': 0,
  'powerup_existe': 1},
 {'bomba_existe': 1,
  'bomba_player': 1,
  'dist_bomba1': 1,
  'dist_bomba2': 1,
  'dist_bomba3': 11,
  'dist_bomba4': 2,
  'dist_jogador1': 0,
  'dist_jogador2': 2,
  'dist_jogador3': 12,
  'dist_jogador4': 4,
  'dist_powerup': 0,
  'funcao': 'fugir',
  'mais_de_um_jogador_perto': 1,
  'neutro': 0,
  'oportunidade': 0,
  'perigo': 1,
  'player_com_powerup': 0,
  'powerup_existe': 0},
 {'bomba_existe': 1,
  'bomba_player': 1,
  'dist_bomba1': 3,
  'dist_bomba2': 5,
  'dist_bomba3': 1,
  'dist_bomba4': 7,
  'dist_jogador1': 0,
  'dist_jogador2': 5,
  'dist_jogador3': 1,
  'dist_jogador4': 7,
  'dist_powerup': 0,
  'funcao': 'fugir',
  'mais_de_um_jogador_perto': 1,
  'neutro': 0,
  'oportunidade': 0,
  'perigo': 1,
  'player_com_powerup': 0,
  'powerup_existe': 0},
 {'bomba_existe': 1,
  'bomba_player': 1,
  'dist_bomba1': 2,
  'dist_bomba2': 3,
  'dist_bomba3': 1,
  'dist_bomba4': 8,
  'dist_jogador1': 0,
  'dist_jogador2': 3,
  'dist_jogador3': 2,
  'dist_jogador4': 10,
  'dist_powerup': 1,
  'funcao': 'fugir',
  'mais_de_um_jogador_perto': 1,
  'neutro': 0,
  'oportunidade': 0,
  'perigo': 1,
  'player_com_powerup': 1,
  'powerup_existe': 1},
 {'bomba_existe': 1,
  'bomba_player': 1,
  'dist_bomba1': 2,
  'dist_bomba2': 6,
  'dist_bomba3': 11,
  'dist_bomba4': 2,
  'dist_jogador1': 0,
  'dist_jogador2': 5,
  'dist_jogador3': 11,
  'dist_jogador4': 3,
  'dist_powerup': 0,
  'funcao': 'fugir',
  'mais_de_um_jogador_perto': 1,
  'neutro': 0,
  'oportunidade': 0,
  'perigo': 1,
  'player_com_powerup': 1,
  'powerup_existe': 0},
 {'bomba_existe': 1,
  'bomba_player': 1,
  'dist_bomba1': 1,
  'dist_bomba2': 3,
  'dist_bomba3': 4,
  'dist_bomba4': 11,
  'dist_jogador1': 0,
  'dist_jogador2': 1,
  'dist_jogador3': 2,
  'dist_jogador4': 9,
  'dist_powerup': 3,
  'funcao': 'fugir',
  'mais_de_um_jogador_perto': 1,
  'neutro': 0,
  'oportunidade': 0,
  'perigo': 1,
  'player_com_powerup': 1,
  'powerup_existe': 1},
{'bomba_existe': 1,
  'bomba_player': 1,
  'dist_bomba1': 3,
  'dist_bomba2': 12,
  'dist_bomba3': 3,
  'dist_bomba4': 8,
  'dist_jogador1': 0,
  'dist_jogador2': 10,
  'dist_jogador3': 2,
  'dist_jogador4': 6,
  'dist_powerup': 0,
  'funcao': 'atacar_e_desviar',
  'mais_de_um_jogador_perto': 0,
  'neutro': 0,
  'oportunidade': 0,
  'perigo': 1,
  'player_com_powerup': 1,
  'powerup_existe': 0},
 {'bomba_existe': 1,
  'bomba_player': 1,
  'dist_bomba1': 3,
  'dist_bomba2': 9,
  'dist_bomba3': 10,
  'dist_bomba4': 5,
  'dist_jogador1': 0,
  'dist_jogador2': 9,
  'dist_jogador3': 11,
  'dist_jogador4': 3,
  'dist_powerup': 2,
  'funcao': 'atacar_e_desviar',
  'mais_de_um_jogador_perto': 0,
  'neutro': 0,
  'oportunidade': 0,
  'perigo': 1,
  'player_com_powerup': 0,
  'powerup_existe': 1},
 {'bomba_existe': 1,
  'bomba_player': 1,
  'dist_bomba1': 2,
  'dist_bomba2': 12,
  'dist_bomba3': 10,
  'dist_bomba4': 13,
  'dist_jogador1': 0,
  'dist_jogador2': 10,
  'dist_jogador3': 9,
  'dist_jogador4': 11,
  'dist_powerup': 0,
  'funcao': 'atacar_e_desviar',
  'mais_de_um_jogador_perto': 0,
  'neutro': 0,
  'oportunidade': 0,
  'perigo': 1,
  'player_com_powerup': 0,
  'powerup_existe': 0},
 {'bomba_existe': 1,
  'bomba_player': 1,
  'dist_bomba1': 3,
  'dist_bomba2': 10,
  'dist_bomba3': 6,
  'dist_bomba4': 8,
  'dist_jogador1': 0,
  'dist_jogador2': 10,
  'dist_jogador3': 8,
  'dist_jogador4': 9,
  'dist_powerup': 7,
  'funcao': 'atacar_e_desviar',
  'mais_de_um_jogador_perto': 0,
  'neutro': 0,
  'oportunidade': 0,
  'perigo': 1,
  'player_com_powerup': 0,
  'powerup_existe': 1},
 {'bomba_existe': 1,
  'bomba_player': 1,
  'dist_bomba1': 2,
  'dist_bomba2': 10,
  'dist_bomba3': 6,
  'dist_bomba4': 9,
  'dist_jogador1': 0,
  'dist_jogador2': 11,
  'dist_jogador3': 5,
  'dist_jogador4': 9,
  'dist_powerup': 1,
  'funcao': 'atacar_e_desviar',
  'mais_de_um_jogador_perto': 0,
  'neutro': 0,
  'oportunidade': 0,
  'perigo': 1,
  'player_com_powerup': 0,
  'powerup_existe': 1},
 {'bomba_existe': 1,
  'bomba_player': 1,
  'dist_bomba1': 3,
  'dist_bomba2': 2,
  'dist_bomba3': 7,
  'dist_bomba4': 10,
  'dist_jogador1': 0,
  'dist_jogador2': 2,
  'dist_jogador3': 9,
  'dist_jogador4': 10,
  'dist_powerup': 9,
  'funcao': 'atacar_e_desviar',
  'mais_de_um_jogador_perto': 0,
  'neutro': 0,
  'oportunidade': 0,
  'perigo': 1,
  'player_com_powerup': 1,
  'powerup_existe': 1},
 {'bomba_existe': 1,
  'bomba_player': 1,
  'dist_bomba1': 1,
  'dist_bomba2': 5,
  'dist_bomba3': 4,
  'dist_bomba4': 12,
  'dist_jogador1': 0,
  'dist_jogador2': 7,
  'dist_jogador3': 4,
  'dist_jogador4': 10,
  'dist_powerup': 9,
  'funcao': 'atacar_e_desviar',
  'mais_de_um_jogador_perto': 0,
  'neutro': 0,
  'oportunidade': 0,
  'perigo': 1,
  'player_com_powerup': 1,
  'powerup_existe': 1},
 {'bomba_existe': 1,
  'bomba_player': 1,
  'dist_bomba1': 2,
  'dist_bomba2': 1,
  'dist_bomba3': 11,
  'dist_bomba4': 9,
  'dist_jogador1': 0,
  'dist_jogador2': 2,
  'dist_jogador3': 9,
  'dist_jogador4': 10,
  'dist_powerup': 7,
  'funcao': 'atacar_e_desviar',
  'mais_de_um_jogador_perto': 0,
  'neutro': 0,
  'oportunidade': 0,
  'perigo': 1,
  'player_com_powerup': 0,
  'powerup_existe': 1},
 {'bomba_existe': 1,
  'bomba_player': 1,
  'dist_bomba1': 1,
  'dist_bomba2': 3,
  'dist_bomba3': 4,
  'dist_bomba4': 7,
  'dist_jogador1': 0,
  'dist_jogador2': 3,
  'dist_jogador3': 6,
  'dist_jogador4': 7,
  'dist_powerup': 4,
  'funcao': 'atacar_e_desviar',
  'mais_de_um_jogador_perto': 0,
  'neutro': 0,
  'oportunidade': 0,
  'perigo': 1,
  'player_com_powerup': 0,
  'powerup_existe': 1},
 {'bomba_existe': 1,
  'bomba_player': 1,
  'dist_bomba1': 1,
  'dist_bomba2': 7,
  'dist_bomba3': 1,
  'dist_bomba4': 9,
  'dist_jogador1': 0,
  'dist_jogador2': 7,
  'dist_jogador3': 2,
  'dist_jogador4': 9,
  'dist_powerup': 5,
  'funcao': 'atacar_e_desviar',
  'mais_de_um_jogador_perto': 0,
  'neutro': 0,
  'oportunidade': 0,
  'perigo': 1,
  'player_com_powerup': 0,
  'powerup_existe': 1},
 {'bomba_existe': 1,
  'bomba_player': 1,
  'dist_bomba1': 1,
  'dist_bomba2': 3,
  'dist_bomba3': 9,
  'dist_bomba4': 6,
  'dist_jogador1': 0,
  'dist_jogador2': 4,
  'dist_jogador3': 9,
  'dist_jogador4': 7,
  'dist_powerup': 1,
  'funcao': 'atacar_e_desviar',
  'mais_de_um_jogador_perto': 0,
  'neutro': 0,
  'oportunidade': 0,
  'perigo': 1,
  'player_com_powerup': 0,
  'powerup_existe': 1},
 {'bomba_existe': 1,
  'bomba_player': 1,
  'dist_bomba1': 2,
  'dist_bomba2': 1,
  'dist_bomba3': 8,
  'dist_bomba4': 8,
  'dist_jogador1': 0,
  'dist_jogador2': 1,
  'dist_jogador3': 9,
  'dist_jogador4': 6,
  'dist_powerup': 9,
  'funcao': 'atacar_e_desviar',
  'mais_de_um_jogador_perto': 0,
  'neutro': 0,
  'oportunidade': 0,
  'perigo': 1,
  'player_com_powerup': 0,
  'powerup_existe': 1},
 {'bomba_existe': 1,
  'bomba_player': 1,
  'dist_bomba1': 2,
  'dist_bomba2': 7,
  'dist_bomba3': 10,
  'dist_bomba4': 11,
  'dist_jogador1': 0,
  'dist_jogador2': 7,
  'dist_jogador3': 9,
  'dist_jogador4': 9,
  'dist_powerup': 0,
  'funcao': 'atacar_e_desviar',
  'mais_de_um_jogador_perto': 0,
  'neutro': 0,
  'oportunidade': 0,
  'perigo': 1,
  'player_com_powerup': 0,
  'powerup_existe': 0},
 {'bomba_existe': 1,
  'bomba_player': 1,
  'dist_bomba1': 1,
  'dist_bomba2': 8,
  'dist_bomba3': 8,
  'dist_bomba4': 2,
  'dist_jogador1': 0,
  'dist_jogador2': 6,
  'dist_jogador3': 10,
  'dist_jogador4': 3,
  'dist_powerup': 0,
  'funcao': 'atacar_e_desviar',
  'mais_de_um_jogador_perto': 0,
  'neutro': 0,
  'oportunidade': 0,
  'perigo': 1,
  'player_com_powerup': 1,
  'powerup_existe': 0},
 {'bomba_existe': 1,
  'bomba_player': 1,
  'dist_bomba1': 3,
  'dist_bomba2': 7,
  'dist_bomba3': 3,
  'dist_bomba4': 6,
  'dist_jogador1': 0,
  'dist_jogador2': 6,
  'dist_jogador3': 4,
  'dist_jogador4': 8,
  'dist_powerup': 0,
  'funcao': 'atacar_e_desviar',
  'mais_de_um_jogador_perto': 0,
  'neutro': 0,
  'oportunidade': 0,
  'perigo': 1,
  'player_com_powerup': 0,
  'powerup_existe': 0},
 {'bomba_existe': 1,
  'bomba_player': 1,
  'dist_bomba1': 2,
  'dist_bomba2': 11,
  'dist_bomba3': 1,
  'dist_bomba4': 10,
  'dist_jogador1': 0,
  'dist_jogador2': 11,
  'dist_jogador3': 1,
  'dist_jogador4': 11,
  'dist_powerup': 4,
  'funcao': 'atacar_e_desviar',
  'mais_de_um_jogador_perto': 0,
  'neutro': 0,
  'oportunidade': 0,
  'perigo': 1,
  'player_com_powerup': 1,
  'powerup_existe': 1},
 {'bomba_existe': 1,
  'bomba_player': 1,
  'dist_bomba1': 2,
  'dist_bomba2': 9,
  'dist_bomba3': 3,
  'dist_bomba4': 12,
  'dist_jogador1': 0,
  'dist_jogador2': 11,
  'dist_jogador3': 4,
  'dist_jogador4': 11,
  'dist_powerup': 0,
  'funcao': 'atacar_e_desviar',
  'mais_de_um_jogador_perto': 0,
  'neutro': 0,
  'oportunidade': 0,
  'perigo': 1,
  'player_com_powerup': 1,
  'powerup_existe': 0},
 {'bomba_existe': 1,
  'bomba_player': 1,
  'dist_bomba1': 3,
  'dist_bomba2': 5,
  'dist_bomba3': 11,
  'dist_bomba4': 3,
  'dist_jogador1': 0,
  'dist_jogador2': 7,
  'dist_jogador3': 12,
  'dist_jogador4': 3,
  'dist_powerup': 0,
  'funcao': 'atacar_e_desviar',
  'mais_de_um_jogador_perto': 0,
  'neutro': 0,
  'oportunidade': 0,
  'perigo': 1,
  'player_com_powerup': 0,
  'powerup_existe': 0},
 {'bomba_existe': 1,
  'bomba_player': 1,
  'dist_bomba1': 3,
  'dist_bomba2': 8,
  'dist_bomba3': 1,
  'dist_bomba4': 6,
  'dist_jogador1': 0,
  'dist_jogador2': 10,
  'dist_jogador3': 2,
  'dist_jogador4': 6,
  'dist_powerup': 11,
  'funcao': 'atacar_e_desviar',
  'mais_de_um_jogador_perto': 0,
  'neutro': 0,
  'oportunidade': 0,
  'perigo': 1,
  'player_com_powerup': 0,
  'powerup_existe': 1},
 {'bomba_existe': 1,
  'bomba_player': 1,
  'dist_bomba1': 3,
  'dist_bomba2': 9,
  'dist_bomba3': 7,
  'dist_bomba4': 11,
  'dist_jogador1': 0,
  'dist_jogador2': 7,
  'dist_jogador3': 5,
  'dist_jogador4': 12,
  'dist_powerup': 3,
  'funcao': 'atacar_e_desviar',
  'mais_de_um_jogador_perto': 0,
  'neutro': 0,
  'oportunidade': 0,
  'perigo': 1,
  'player_com_powerup': 0,
  'powerup_existe': 1},
 {'bomba_existe': 1,
  'bomba_player': 1,
  'dist_bomba1': 2,
  'dist_bomba2': 8,
  'dist_bomba3': 13,
  'dist_bomba4': 5,
  'dist_jogador1': 0,
  'dist_jogador2': 10,
  'dist_jogador3': 12,
  'dist_jogador4': 4,
  'dist_powerup': 0,
  'funcao': 'atacar_e_desviar',
  'mais_de_um_jogador_perto': 0,
  'neutro': 0,
  'oportunidade': 0,
  'perigo': 1,
  'player_com_powerup': 0,
  'powerup_existe': 0},
 {'bomba_existe': 1,
  'bomba_player': 1,
  'dist_bomba1': 3,
  'dist_bomba2': 12,
  'dist_bomba3': 11,
  'dist_bomba4': 4,
  'dist_jogador1': 0,
  'dist_jogador2': 12,
  'dist_jogador3': 10,
  'dist_jogador4': 4,
  'dist_powerup': 0,
  'funcao': 'atacar_e_desviar',
  'mais_de_um_jogador_perto': 0,
  'neutro': 0,
  'oportunidade': 0,
  'perigo': 1,
  'player_com_powerup': 1,
  'powerup_existe': 0},
 {'bomba_existe': 1,
  'bomba_player': 1,
  'dist_bomba1': 3,
  'dist_bomba2': 8,
  'dist_bomba3': 11,
  'dist_bomba4': 6,
  'dist_jogador1': 0,
  'dist_jogador2': 8,
  'dist_jogador3': 10,
  'dist_jogador4': 6,
  'dist_powerup': 3,
  'funcao': 'atacar_e_desviar',
  'mais_de_um_jogador_perto': 0,
  'neutro': 0,
  'oportunidade': 0,
  'perigo': 1,
  'player_com_powerup': 0,
  'powerup_existe': 1},
 {'bomba_existe': 1,
  'bomba_player': 1,
  'dist_bomba1': 1,
  'dist_bomba2': 10,
  'dist_bomba3': 9,
  'dist_bomba4': 1,
  'dist_jogador1': 0,
  'dist_jogador2': 8,
  'dist_jogador3': 8,
  'dist_jogador4': 1,
  'dist_powerup': 4,
  'funcao': 'atacar_e_desviar',
  'mais_de_um_jogador_perto': 0,
  'neutro': 0,
  'oportunidade': 0,
  'perigo': 1,
  'player_com_powerup': 1,
  'powerup_existe': 1},
 {'bomba_existe': 1,
  'bomba_player': 1,
  'dist_bomba1': 2,
  'dist_bomba2': 10,
  'dist_bomba3': 7,
  'dist_bomba4': 5,
  'dist_jogador1': 0,
  'dist_jogador2': 11,
  'dist_jogador3': 6,
  'dist_jogador4': 7,
  'dist_powerup': 0,
  'funcao': 'atacar_e_desviar',
  'mais_de_um_jogador_perto': 0,
  'neutro': 0,
  'oportunidade': 0,
  'perigo': 1,
  'player_com_powerup': 0,
  'powerup_existe': 0},
 {'bomba_existe': 1,
  'bomba_player': 1,
  'dist_bomba1': 1,
  'dist_bomba2': 5,
  'dist_bomba3': 11,
  'dist_bomba4': 8,
  'dist_jogador1': 0,
  'dist_jogador2': 5,
  'dist_jogador3': 11,
  'dist_jogador4': 7,
  'dist_powerup': 2,
  'funcao': 'atacar_e_desviar',
  'mais_de_um_jogador_perto': 0,
  'neutro': 0,
  'oportunidade': 0,
  'perigo': 1,
  'player_com_powerup': 1,
  'powerup_existe': 1},
 {'bomba_existe': 1,
  'bomba_player': 1,
  'dist_bomba1': 1,
  'dist_bomba2': 7,
  'dist_bomba3': 5,
  'dist_bomba4': 8,
  'dist_jogador1': 0,
  'dist_jogador2': 8,
  'dist_jogador3': 4,
  'dist_jogador4': 7,
  'dist_powerup': 0,
  'funcao': 'atacar_e_desviar',
  'mais_de_um_jogador_perto': 0,
  'neutro': 0,
  'oportunidade': 0,
  'perigo': 1,
  'player_com_powerup': 0,
  'powerup_existe': 0},
 {'bomba_existe': 1,
  'bomba_player': 1,
  'dist_bomba1': 1,
  'dist_bomba2': 2,
  'dist_bomba3': 5,
  'dist_bomba4': 8,
  'dist_jogador1': 0,
  'dist_jogador2': 2,
  'dist_jogador3': 6,
  'dist_jogador4': 7,
  'dist_powerup': 0,
  'funcao': 'atacar_e_desviar',
  'mais_de_um_jogador_perto': 0,
  'neutro': 0,
  'oportunidade': 0,
  'perigo': 1,
  'player_com_powerup': 1,
  'powerup_existe': 0},
 {'bomba_existe': 1,
  'bomba_player': 1,
  'dist_bomba1': 2,
  'dist_bomba2': 7,
  'dist_bomba3': 3,
  'dist_bomba4': 13,
  'dist_jogador1': 0,
  'dist_jogador2': 7,
  'dist_jogador3': 1,
  'dist_jogador4': 11,
  'dist_powerup': 6,
  'funcao': 'atacar_e_desviar',
  'mais_de_um_jogador_perto': 0,
  'neutro': 0,
  'oportunidade': 0,
  'perigo': 1,
  'player_com_powerup': 0,
  'powerup_existe': 1},
 {'bomba_existe': 1,
  'bomba_player': 1,
  'dist_bomba1': 3,
  'dist_bomba2': 6,
  'dist_bomba3': 4,
  'dist_bomba4': 8,
  'dist_jogador1': 0,
  'dist_jogador2': 5,
  'dist_jogador3': 6,
  'dist_jogador4': 8,
  'dist_powerup': 7,
  'funcao': 'atacar_e_desviar',
  'mais_de_um_jogador_perto': 0,
  'neutro': 0,
  'oportunidade': 0,
  'perigo': 1,
  'player_com_powerup': 1,
  'powerup_existe': 1},
 {'bomba_existe': 1,
  'bomba_player': 1,
  'dist_bomba1': 3,
  'dist_bomba2': 7,
  'dist_bomba3': 10,
  'dist_bomba4': 8,
  'dist_jogador1': 0,
  'dist_jogador2': 9,
  'dist_jogador3': 8,
  'dist_jogador4': 9,
  'dist_powerup': 0,
  'funcao': 'atacar_e_desviar',
  'mais_de_um_jogador_perto': 0,
  'neutro': 0,
  'oportunidade': 0,
  'perigo': 1,
  'player_com_powerup': 1,
  'powerup_existe': 0
 },
 {'bomba_existe': 1,
  'bomba_player': 0,
  'dist_bomba1': 0,
  'dist_bomba2': 12,
  'dist_bomba3': 6,
  'dist_bomba4': 3,
  'dist_jogador1': 0,
  'dist_jogador2': 12,
  'dist_jogador3': 7,
  'dist_jogador4': 2,
  'dist_powerup': 0,
  'funcao': 'atacar_e_desviar',
  'mais_de_um_jogador_perto': 0,
  'neutro': 0,
  'oportunidade': 0,
  'perigo': 1,
  'player_com_powerup': 1,
  'powerup_existe': 0},
 {'bomba_existe': 1,
  'bomba_player': 0,
  'dist_bomba1': 0,
  'dist_bomba2': 8,
  'dist_bomba3': 13,
  'dist_bomba4': 8,
  'dist_jogador1': 0,
  'dist_jogador2': 6,
  'dist_jogador3': 11,
  'dist_jogador4': 9,
  'dist_powerup': 12,
  'funcao': 'atacar_e_desviar',
  'mais_de_um_jogador_perto': 0,
  'neutro': 0,
  'oportunidade': 0,
  'perigo': 1,
  'player_com_powerup': 1,
  'powerup_existe': 1},
 {'bomba_existe': 1,
  'bomba_player': 0,
  'dist_bomba1': 0,
  'dist_bomba2': 13,
  'dist_bomba3': 4,
  'dist_bomba4': 12,
  'dist_jogador1': 0,
  'dist_jogador2': 12,
  'dist_jogador3': 6,
  'dist_jogador4': 10,
  'dist_powerup': 1,
  'funcao': 'atacar_e_desviar',
  'mais_de_um_jogador_perto': 0,
  'neutro': 0,
  'oportunidade': 0,
  'perigo': 1,
  'player_com_powerup': 1,
  'powerup_existe': 1},
 {'bomba_existe': 1,
  'bomba_player': 0,
  'dist_bomba1': 0,
  'dist_bomba2': 3,
  'dist_bomba3': 10,
  'dist_bomba4': 8,
  'dist_jogador1': 0,
  'dist_jogador2': 2,
  'dist_jogador3': 12,
  'dist_jogador4': 9,
  'dist_powerup': 3,
  'funcao': 'atacar_e_desviar',
  'mais_de_um_jogador_perto': 0,
  'neutro': 0,
  'oportunidade': 0,
  'perigo': 1,
  'player_com_powerup': 0,
  'powerup_existe': 1},
 {'bomba_existe': 1,
  'bomba_player': 0,
  'dist_bomba1': 0,
  'dist_bomba2': 9,
  'dist_bomba3': 2,
  'dist_bomba4': 8,
  'dist_jogador1': 0,
  'dist_jogador2': 9,
  'dist_jogador3': 2,
  'dist_jogador4': 7,
  'dist_powerup': 0,
  'funcao': 'atacar_e_desviar',
  'mais_de_um_jogador_perto': 0,
  'neutro': 0,
  'oportunidade': 0,
  'perigo': 1,
  'player_com_powerup': 1,
  'powerup_existe': 0},
 {'bomba_existe': 1,
  'bomba_player': 0,
  'dist_bomba1': 0,
  'dist_bomba2': 9,
  'dist_bomba3': 12,
  'dist_bomba4': 3,
  'dist_jogador1': 0,
  'dist_jogador2': 10,
  'dist_jogador3': 11,
  'dist_jogador4': 3,
  'dist_powerup': 5,
  'funcao': 'atacar_e_desviar',
  'mais_de_um_jogador_perto': 0,
  'neutro': 0,
  'oportunidade': 0,
  'perigo': 1,
  'player_com_powerup': 0,
  'powerup_existe': 1},
 {'bomba_existe': 1,
  'bomba_player': 0,
  'dist_bomba1': 0,
  'dist_bomba2': 8,
  'dist_bomba3': 12,
  'dist_bomba4': 1,
  'dist_jogador1': 0,
  'dist_jogador2': 7,
  'dist_jogador3': 11,
  'dist_jogador4': 2,
  'dist_powerup': 5,
  'funcao': 'atacar_e_desviar',
  'mais_de_um_jogador_perto': 0,
  'neutro': 0,
  'oportunidade': 0,
  'perigo': 1,
  'player_com_powerup': 0,
  'powerup_existe': 1},
 {'bomba_existe': 1,
  'bomba_player': 0,
  'dist_bomba1': 0,
  'dist_bomba2': 3,
  'dist_bomba3': 6,
  'dist_bomba4': 6,
  'dist_jogador1': 0,
  'dist_jogador2': 2,
  'dist_jogador3': 8,
  'dist_jogador4': 8,
  'dist_powerup': 7,
  'funcao': 'atacar_e_desviar',
  'mais_de_um_jogador_perto': 0,
  'neutro': 0,
  'oportunidade': 0,
  'perigo': 1,
  'player_com_powerup': 0,
  'powerup_existe': 1},
 {'bomba_existe': 1,
  'bomba_player': 0,
  'dist_bomba1': 0,
  'dist_bomba2': 4,
  'dist_bomba3': 3,
  'dist_bomba4': 12,
  'dist_jogador1': 0,
  'dist_jogador2': 6,
  'dist_jogador3': 4,
  'dist_jogador4': 12,
  'dist_powerup': 5,
  'funcao': 'atacar_e_desviar',
  'mais_de_um_jogador_perto': 0,
  'neutro': 0,
  'oportunidade': 0,
  'perigo': 1,
  'player_com_powerup': 0,
  'powerup_existe': 1},
 {'bomba_existe': 1,
  'bomba_player': 0,
  'dist_bomba1': 0,
  'dist_bomba2': 6,
  'dist_bomba3': 5,
  'dist_bomba4': 7,
  'dist_jogador1': 0,
  'dist_jogador2': 8,
  'dist_jogador3': 7,
  'dist_jogador4': 5,
  'dist_powerup': 0,
  'funcao': 'atacar_e_desviar',
  'mais_de_um_jogador_perto': 0,
  'neutro': 0,
  'oportunidade': 0,
  'perigo': 1,
  'player_com_powerup': 1,
  'powerup_existe': 0},
 {'bomba_existe': 1,
  'bomba_player': 0,
  'dist_bomba1': 0,
  'dist_bomba2': 8,
  'dist_bomba3': 5,
  'dist_bomba4': 7,
  'dist_jogador1': 0,
  'dist_jogador2': 10,
  'dist_jogador3': 6,
  'dist_jogador4': 9,
  'dist_powerup': 4,
  'funcao': 'atacar_e_desviar',
  'mais_de_um_jogador_perto': 0,
  'neutro': 0,
  'oportunidade': 0,
  'perigo': 1,
  'player_com_powerup': 1,
  'powerup_existe': 1},
 {'bomba_existe': 1,
  'bomba_player': 0,
  'dist_bomba1': 0,
  'dist_bomba2': 4,
  'dist_bomba3': 5,
  'dist_bomba4': 7,
  'dist_jogador1': 0,
  'dist_jogador2': 6,
  'dist_jogador3': 5,
  'dist_jogador4': 9,
  'dist_powerup': 6,
  'funcao': 'atacar_e_desviar',
  'mais_de_um_jogador_perto': 0,
  'neutro': 0,
  'oportunidade': 0,
  'perigo': 1,
  'player_com_powerup': 0,
  'powerup_existe': 1},
 {'bomba_existe': 1,
  'bomba_player': 0,
  'dist_bomba1': 0,
  'dist_bomba2': 11,
  'dist_bomba3': 13,
  'dist_bomba4': 6,
  'dist_jogador1': 0,
  'dist_jogador2': 12,
  'dist_jogador3': 11,
  'dist_jogador4': 7,
  'dist_powerup': 0,
  'funcao': 'atacar_e_desviar',
  'mais_de_um_jogador_perto': 0,
  'neutro': 0,
  'oportunidade': 0,
  'perigo': 1,
  'player_com_powerup': 0,
  'powerup_existe': 0},
 {'bomba_existe': 1,
  'bomba_player': 0,
  'dist_bomba1': 0,
  'dist_bomba2': 8,
  'dist_bomba3': 1,
  'dist_bomba4': 7,
  'dist_jogador1': 0,
  'dist_jogador2': 7,
  'dist_jogador3': 2,
  'dist_jogador4': 7,
  'dist_powerup': 0,
  'funcao': 'atacar_e_desviar',
  'mais_de_um_jogador_perto': 0,
  'neutro': 0,
  'oportunidade': 0,
  'perigo': 1,
  'player_com_powerup': 0,
  'powerup_existe': 0},
 {'bomba_existe': 1,
  'bomba_player': 0,
  'dist_bomba1': 0,
  'dist_bomba2': 3,
  'dist_bomba3': 8,
  'dist_bomba4': 11,
  'dist_jogador1': 0,
  'dist_jogador2': 4,
  'dist_jogador3': 9,
  'dist_jogador4': 12,
  'dist_powerup': 9,
  'funcao': 'atacar_e_desviar',
  'mais_de_um_jogador_perto': 0,
  'neutro': 0,
  'oportunidade': 0,
  'perigo': 1,
  'player_com_powerup': 1,
  'powerup_existe': 1},
 {'bomba_existe': 1,
  'bomba_player': 0,
  'dist_bomba1': 0,
  'dist_bomba2': 2,
  'dist_bomba3': 9,
  'dist_bomba4': 9,
  'dist_jogador1': 0,
  'dist_jogador2': 4,
  'dist_jogador3': 9,
  'dist_jogador4': 9,
  'dist_powerup': 9,
  'funcao': 'atacar_e_desviar',
  'mais_de_um_jogador_perto': 0,
  'neutro': 0,
  'oportunidade': 0,
  'perigo': 1,
  'player_com_powerup': 0,
  'powerup_existe': 1},
 {'bomba_existe': 1,
  'bomba_player': 0,
  'dist_bomba1': 0,
  'dist_bomba2': 4,
  'dist_bomba3': 5,
  'dist_bomba4': 8,
  'dist_jogador1': 0,
  'dist_jogador2': 3,
  'dist_jogador3': 7,
  'dist_jogador4': 7,
  'dist_powerup': 3,
  'funcao': 'atacar_e_desviar',
  'mais_de_um_jogador_perto': 0,
  'neutro': 0,
  'oportunidade': 0,
  'perigo': 1,
  'player_com_powerup': 0,
  'powerup_existe': 1},
 {'bomba_existe': 1,
  'bomba_player': 0,
  'dist_bomba1': 0,
  'dist_bomba2': 11,
  'dist_bomba3': 13,
  'dist_bomba4': 6,
  'dist_jogador1': 0,
  'dist_jogador2': 12,
  'dist_jogador3': 12,
  'dist_jogador4': 4,
  'dist_powerup': 6,
  'funcao': 'atacar_e_desviar',
  'mais_de_um_jogador_perto': 0,
  'neutro': 0,
  'oportunidade': 0,
  'perigo': 1,
  'player_com_powerup': 0,
  'powerup_existe': 1},
 {'bomba_existe': 1,
  'bomba_player': 0,
  'dist_bomba1': 0,
  'dist_bomba2': 4,
  'dist_bomba3': 9,
  'dist_bomba4': 8,
  'dist_jogador1': 0,
  'dist_jogador2': 3,
  'dist_jogador3': 10,
  'dist_jogador4': 6,
  'dist_powerup': 12,
  'funcao': 'atacar_e_desviar',
  'mais_de_um_jogador_perto': 0,
  'neutro': 0,
  'oportunidade': 0,
  'perigo': 1,
  'player_com_powerup': 0,
  'powerup_existe': 1},
 {'bomba_existe': 1,
  'bomba_player': 0,
  'dist_bomba1': 0,
  'dist_bomba2': 1,
  'dist_bomba3': 6,
  'dist_bomba4': 4,
  'dist_jogador1': 0,
  'dist_jogador2': 2,
  'dist_jogador3': 7,
  'dist_jogador4': 6,
  'dist_powerup': 6,
  'funcao': 'atacar_e_desviar',
  'mais_de_um_jogador_perto': 0,
  'neutro': 0,
  'oportunidade': 0,
  'perigo': 1,
  'player_com_powerup': 1,
  'powerup_existe': 1},
 {'bomba_existe': 1,
  'bomba_player': 0,
  'dist_bomba1': 0,
  'dist_bomba2': 10,
  'dist_bomba3': 7,
  'dist_bomba4': 2,
  'dist_jogador1': 0,
  'dist_jogador2': 11,
  'dist_jogador3': 8,
  'dist_jogador4': 2,
  'dist_powerup': 0,
  'funcao': 'atacar_e_desviar',
  'mais_de_um_jogador_perto': 0,
  'neutro': 0,
  'oportunidade': 0,
  'perigo': 1,
  'player_com_powerup': 1,
  'powerup_existe': 0},
 {'bomba_existe': 1,
  'bomba_player': 0,
  'dist_bomba1': 0,
  'dist_bomba2': 9,
  'dist_bomba3': 1,
  'dist_bomba4': 5,
  'dist_jogador1': 0,
  'dist_jogador2': 7,
  'dist_jogador3': 2,
  'dist_jogador4': 6,
  'dist_powerup': 7,
  'funcao': 'atacar_e_desviar',
  'mais_de_um_jogador_perto': 0,
  'neutro': 0,
  'oportunidade': 0,
  'perigo': 1,
  'player_com_powerup': 1,
  'powerup_existe': 1},
 {'bomba_existe': 1,
  'bomba_player': 0,
  'dist_bomba1': 0,
  'dist_bomba2': 5,
  'dist_bomba3': 10,
  'dist_bomba4': 7,
  'dist_jogador1': 0,
  'dist_jogador2': 7,
  'dist_jogador3': 12,
  'dist_jogador4': 6,
  'dist_powerup': 7,
  'funcao': 'atacar_e_desviar',
  'mais_de_um_jogador_perto': 0,
  'neutro': 0,
  'oportunidade': 0,
  'perigo': 1,
  'player_com_powerup': 1,
  'powerup_existe': 1},
 {'bomba_existe': 1,
  'bomba_player': 0,
  'dist_bomba1': 0,
  'dist_bomba2': 4,
  'dist_bomba3': 5,
  'dist_bomba4': 8,
  'dist_jogador1': 0,
  'dist_jogador2': 4,
  'dist_jogador3': 6,
  'dist_jogador4': 7,
  'dist_powerup': 10,
  'funcao': 'atacar_e_desviar',
  'mais_de_um_jogador_perto': 0,
  'neutro': 0,
  'oportunidade': 0,
  'perigo': 1,
  'player_com_powerup': 1,
  'powerup_existe': 1},
 {'bomba_existe': 1,
  'bomba_player': 0,
  'dist_bomba1': 0,
  'dist_bomba2': 9,
  'dist_bomba3': 3,
  'dist_bomba4': 11,
  'dist_jogador1': 0,
  'dist_jogador2': 11,
  'dist_jogador3': 3,
  'dist_jogador4': 12,
  'dist_powerup': 0,
  'funcao': 'atacar_e_desviar',
  'mais_de_um_jogador_perto': 0,
  'neutro': 0,
  'oportunidade': 0,
  'perigo': 1,
  'player_com_powerup': 1,
  'powerup_existe': 0},
 {'bomba_existe': 1,
  'bomba_player': 0,
  'dist_bomba1': 0,
  'dist_bomba2': 7,
  'dist_bomba3': 2,
  'dist_bomba4': 6,
  'dist_jogador1': 0,
  'dist_jogador2': 8,
  'dist_jogador3': 4,
  'dist_jogador4': 8,
  'dist_powerup': 1,
  'funcao': 'atacar_e_desviar',
  'mais_de_um_jogador_perto': 0,
  'neutro': 0,
  'oportunidade': 0,
  'perigo': 1,
  'player_com_powerup': 0,
  'powerup_existe': 1},
 {'bomba_existe': 0,
  'bomba_player': 0,
  'dist_bomba1': 0,
  'dist_bomba2': 0,
  'dist_bomba3': 0,
  'dist_bomba4': 0,
  'dist_jogador1': 0,
  'dist_jogador2': 7,
  'dist_jogador3': 8,
  'dist_jogador4': 11,
  'dist_powerup': 0,
  'funcao': 'atacar_e_desviar',
  'mais_de_um_jogador_perto': 0,
  'neutro': 0,
  'oportunidade': 0,
  'perigo': 1,
  'player_com_powerup': 0,
  'powerup_existe': 0},
 {'bomba_existe': 0,
  'bomba_player': 0,
  'dist_bomba1': 0,
  'dist_bomba2': 0,
  'dist_bomba3': 0,
  'dist_bomba4': 0,
  'dist_jogador1': 0,
  'dist_jogador2': 1,
  'dist_jogador3': 9,
  'dist_jogador4': 10,
  'dist_powerup': 0,
  'funcao': 'atacar_e_desviar',
  'mais_de_um_jogador_perto': 0,
  'neutro': 0,
  'oportunidade': 0,
  'perigo': 1,
  'player_com_powerup': 1,
  'powerup_existe': 0},
 {'bomba_existe': 0,
  'bomba_player': 0,
  'dist_bomba1': 0,
  'dist_bomba2': 0,
  'dist_bomba3': 0,
  'dist_bomba4': 0,
  'dist_jogador1': 0,
  'dist_jogador2': 6,
  'dist_jogador3': 9,
  'dist_jogador4': 11,
  'dist_powerup': 0,
  'funcao': 'atacar_e_desviar',
  'mais_de_um_jogador_perto': 0,
  'neutro': 0,
  'oportunidade': 0,
  'perigo': 1,
  'player_com_powerup': 1,
  'powerup_existe': 0},
 {'bomba_existe': 0,
  'bomba_player': 0,
  'dist_bomba1': 0,
  'dist_bomba2': 0,
  'dist_bomba3': 0,
  'dist_bomba4': 0,
  'dist_jogador1': 0,
  'dist_jogador2': 3,
  'dist_jogador3': 12,
  'dist_jogador4': 8,
  'dist_powerup': 5,
  'funcao': 'atacar_e_desviar',
  'mais_de_um_jogador_perto': 0,
  'neutro': 0,
  'oportunidade': 0,
  'perigo': 1,
  'player_com_powerup': 1,
  'powerup_existe': 1},
 {'bomba_existe': 0,
  'bomba_player': 0,
  'dist_bomba1': 0,
  'dist_bomba2': 0,
  'dist_bomba3': 0,
  'dist_bomba4': 0,
  'dist_jogador1': 0,
  'dist_jogador2': 6,
  'dist_jogador3': 7,
  'dist_jogador4': 6,
  'dist_powerup': 0,
  'funcao': 'atacar_e_desviar',
  'mais_de_um_jogador_perto': 0,
  'neutro': 0,
  'oportunidade': 0,
  'perigo': 1,
  'player_com_powerup': 0,
  'powerup_existe': 0},
 {'bomba_existe': 0,
  'bomba_player': 0,
  'dist_bomba1': 0,
  'dist_bomba2': 0,
  'dist_bomba3': 0,
  'dist_bomba4': 0,
  'dist_jogador1': 0,
  'dist_jogador2': 7,
  'dist_jogador3': 6,
  'dist_jogador4': 1,
  'dist_powerup': 0,
  'funcao': 'atacar_e_desviar',
  'mais_de_um_jogador_perto': 0,
  'neutro': 0,
  'oportunidade': 0,
  'perigo': 1,
  'player_com_powerup': 1,
  'powerup_existe': 0},
 {'bomba_existe': 0,
  'bomba_player': 0,
  'dist_bomba1': 0,
  'dist_bomba2': 0,
  'dist_bomba3': 0,
  'dist_bomba4': 0,
  'dist_jogador1': 0,
  'dist_jogador2': 3,
  'dist_jogador3': 6,
  'dist_jogador4': 7,
  'dist_powerup': 5,
  'funcao': 'atacar_e_desviar',
  'mais_de_um_jogador_perto': 0,
  'neutro': 0,
  'oportunidade': 0,
  'perigo': 1,
  'player_com_powerup': 1,
  'powerup_existe': 1},
 {'bomba_existe': 0,
  'bomba_player': 0,
  'dist_bomba1': 0,
  'dist_bomba2': 0,
  'dist_bomba3': 0,
  'dist_bomba4': 0,
  'dist_jogador1': 0,
  'dist_jogador2': 6,
  'dist_jogador3': 6,
  'dist_jogador4': 2,
  'dist_powerup': 0,
  'funcao': 'atacar_e_desviar',
  'mais_de_um_jogador_perto': 0,
  'neutro': 0,
  'oportunidade': 0,
  'perigo': 1,
  'player_com_powerup': 1,
  'powerup_existe': 0},
 {'bomba_existe': 0,
  'bomba_player': 0,
  'dist_bomba1': 0,
  'dist_bomba2': 0,
  'dist_bomba3': 0,
  'dist_bomba4': 0,
  'dist_jogador1': 0,
  'dist_jogador2': 3,
  'dist_jogador3': 10,
  'dist_jogador4': 7,
  'dist_powerup': 0,
  'funcao': 'atacar_e_desviar',
  'mais_de_um_jogador_perto': 0,
  'neutro': 0,
  'oportunidade': 0,
  'perigo': 1,
  'player_com_powerup': 1,
  'powerup_existe': 0},
 {'bomba_existe': 0,
  'bomba_player': 0,
  'dist_bomba1': 0,
  'dist_bomba2': 0,
  'dist_bomba3': 0,
  'dist_bomba4': 0,
  'dist_jogador1': 0,
  'dist_jogador2': 9,
  'dist_jogador3': 3,
  'dist_jogador4': 11,
  'dist_powerup': 0,
  'funcao': 'atacar_e_desviar',
  'mais_de_um_jogador_perto': 0,
  'neutro': 0,
  'oportunidade': 0,
  'perigo': 1,
  'player_com_powerup': 0,
  'powerup_existe': 0},
 {'bomba_existe': 0,
  'bomba_player': 0,
  'dist_bomba1': 0,
  'dist_bomba2': 0,
  'dist_bomba3': 0,
  'dist_bomba4': 0,
  'dist_jogador1': 0,
  'dist_jogador2': 8,
  'dist_jogador3': 1,
  'dist_jogador4': 9,
  'dist_powerup': 0,
  'funcao': 'atacar_e_desviar',
  'mais_de_um_jogador_perto': 0,
  'neutro': 0,
  'oportunidade': 0,
  'perigo': 1,
  'player_com_powerup': 1,
  'powerup_existe': 0},
 {'bomba_existe': 0,
  'bomba_player': 0,
  'dist_bomba1': 0,
  'dist_bomba2': 0,
  'dist_bomba3': 0,
  'dist_bomba4': 0,
  'dist_jogador1': 0,
  'dist_jogador2': 8,
  'dist_jogador3': 12,
  'dist_jogador4': 8,
  'dist_powerup': 0,
  'funcao': 'atacar_e_desviar',
  'mais_de_um_jogador_perto': 0,
  'neutro': 0,
  'oportunidade': 0,
  'perigo': 1,
  'player_com_powerup': 0,
  'powerup_existe': 0},
 {'bomba_existe': 0,
  'bomba_player': 0,
  'dist_bomba1': 0,
  'dist_bomba2': 0,
  'dist_bomba3': 0,
  'dist_bomba4': 0,
  'dist_jogador1': 0,
  'dist_jogador2': 11,
  'dist_jogador3': 9,
  'dist_jogador4': 6,
  'dist_powerup': 4,
  'funcao': 'atacar_e_desviar',
  'mais_de_um_jogador_perto': 0,
  'neutro': 0,
  'oportunidade': 0,
  'perigo': 1,
  'player_com_powerup': 1,
  'powerup_existe': 1},
 {'bomba_existe': 0,
  'bomba_player': 0,
  'dist_bomba1': 0,
  'dist_bomba2': 0,
  'dist_bomba3': 0,
  'dist_bomba4': 0,
  'dist_jogador1': 0,
  'dist_jogador2': 6,
  'dist_jogador3': 6,
  'dist_jogador4': 9,
  'dist_powerup': 0,
  'funcao': 'atacar_e_desviar',
  'mais_de_um_jogador_perto': 0,
  'neutro': 0,
  'oportunidade': 0,
  'perigo': 1,
  'player_com_powerup': 1,
  'powerup_existe': 0},
 {'bomba_existe': 0,
  'bomba_player': 0,
  'dist_bomba1': 0,
  'dist_bomba2': 0,
  'dist_bomba3': 0,
  'dist_bomba4': 0,
  'dist_jogador1': 0,
  'dist_jogador2': 7,
  'dist_jogador3': 7,
  'dist_jogador4': 2,
  'dist_powerup': 0,
  'funcao': 'atacar_e_desviar',
  'mais_de_um_jogador_perto': 0,
  'neutro': 0,
  'oportunidade': 0,
  'perigo': 1,
  'player_com_powerup': 0,
  'powerup_existe': 0},
 {'bomba_existe': 0,
  'bomba_player': 0,
  'dist_bomba1': 0,
  'dist_bomba2': 0,
  'dist_bomba3': 0,
  'dist_bomba4': 0,
  'dist_jogador1': 0,
  'dist_jogador2': 6,
  'dist_jogador3': 7,
  'dist_jogador4': 1,
  'dist_powerup': 10,
  'funcao': 'atacar_e_desviar',
  'mais_de_um_jogador_perto': 0,
  'neutro': 0,
  'oportunidade': 0,
  'perigo': 1,
  'player_com_powerup': 1,
  'powerup_existe': 1},
 {'bomba_existe': 0,
  'bomba_player': 0,
  'dist_bomba1': 0,
  'dist_bomba2': 0,
  'dist_bomba3': 0,
  'dist_bomba4': 0,
  'dist_jogador1': 0,
  'dist_jogador2': 3,
  'dist_jogador3': 10,
  'dist_jogador4': 6,
  'dist_powerup': 0,
  'funcao': 'atacar_e_desviar',
  'mais_de_um_jogador_perto': 0,
  'neutro': 0,
  'oportunidade': 0,
  'perigo': 1,
  'player_com_powerup': 0,
  'powerup_existe': 0},
 {'bomba_existe': 0,
  'bomba_player': 0,
  'dist_bomba1': 0,
  'dist_bomba2': 0,
  'dist_bomba3': 0,
  'dist_bomba4': 0,
  'dist_jogador1': 0,
  'dist_jogador2': 6,
  'dist_jogador3': 12,
  'dist_jogador4': 7,
  'dist_powerup': 0,
  'funcao': 'atacar_e_desviar',
  'mais_de_um_jogador_perto': 0,
  'neutro': 0,
  'oportunidade': 0,
  'perigo': 1,
  'player_com_powerup': 0,
  'powerup_existe': 0},
 {'bomba_existe': 0,
  'bomba_player': 0,
  'dist_bomba1': 0,
  'dist_bomba2': 0,
  'dist_bomba3': 0,
  'dist_bomba4': 0,
  'dist_jogador1': 0,
  'dist_jogador2': 10,
  'dist_jogador3': 8,
  'dist_jogador4': 5,
  'dist_powerup': 0,
  'funcao': 'atacar_e_desviar',
  'mais_de_um_jogador_perto': 0,
  'neutro': 0,
  'oportunidade': 0,
  'perigo': 1,
  'player_com_powerup': 0,
  'powerup_existe': 0},
 {'bomba_existe': 0,
  'bomba_player': 0,
  'dist_bomba1': 0,
  'dist_bomba2': 0,
  'dist_bomba3': 0,
  'dist_bomba4': 0,
  'dist_jogador1': 0,
  'dist_jogador2': 11,
  'dist_jogador3': 9,
  'dist_jogador4': 2,
  'dist_powerup': 5,
  'funcao': 'atacar_e_desviar',
  'mais_de_um_jogador_perto': 0,
  'neutro': 0,
  'oportunidade': 0,
  'perigo': 1,
  'player_com_powerup': 0,
  'powerup_existe': 1},
 {'bomba_existe': 0,
  'bomba_player': 0,
  'dist_bomba1': 0,
  'dist_bomba2': 0,
  'dist_bomba3': 0,
  'dist_bomba4': 0,
  'dist_jogador1': 0,
  'dist_jogador2': 11,
  'dist_jogador3': 9,
  'dist_jogador4': 5,
  'dist_powerup': 12,
  'funcao': 'atacar_e_desviar',
  'mais_de_um_jogador_perto': 0,
  'neutro': 0,
  'oportunidade': 0,
  'perigo': 1,
  'player_com_powerup': 0,
  'powerup_existe': 1},
 {'bomba_existe': 0,
  'bomba_player': 0,
  'dist_bomba1': 0,
  'dist_bomba2': 0,
  'dist_bomba3': 0,
  'dist_bomba4': 0,
  'dist_jogador1': 0,
  'dist_jogador2': 1,
  'dist_jogador3': 6,
  'dist_jogador4': 11,
  'dist_powerup': 0,
  'funcao': 'atacar_e_desviar',
  'mais_de_um_jogador_perto': 0,
  'neutro': 0,
  'oportunidade': 0,
  'perigo': 1,
  'player_com_powerup': 1,
  'powerup_existe': 0},
 {'bomba_existe': 0,
  'bomba_player': 0,
  'dist_bomba1': 0,
  'dist_bomba2': 0,
  'dist_bomba3': 0,
  'dist_bomba4': 0,
  'dist_jogador1': 0,
  'dist_jogador2': 10,
  'dist_jogador3': 8,
  'dist_jogador4': 2,
  'dist_powerup': 0,
  'funcao': 'atacar_e_desviar',
  'mais_de_um_jogador_perto': 0,
  'neutro': 0,
  'oportunidade': 0,
  'perigo': 1,
  'player_com_powerup': 1,
  'powerup_existe': 0},
 {'bomba_existe': 0,
  'bomba_player': 0,
  'dist_bomba1': 0,
  'dist_bomba2': 0,
  'dist_bomba3': 0,
  'dist_bomba4': 0,
  'dist_jogador1': 0,
  'dist_jogador2': 11,
  'dist_jogador3': 10,
  'dist_jogador4': 11,
  'dist_powerup': 8,
  'funcao': 'atacar_e_desviar',
  'mais_de_um_jogador_perto': 0,
  'neutro': 0,
  'oportunidade': 0,
  'perigo': 1,
  'player_com_powerup': 0,
  'powerup_existe': 1},
 {'bomba_existe': 0,
  'bomba_player': 0,
  'dist_bomba1': 0,
  'dist_bomba2': 0,
  'dist_bomba3': 0,
  'dist_bomba4': 0,
  'dist_jogador1': 0,
  'dist_jogador2': 2,
  'dist_jogador3': 12,
  'dist_jogador4': 9,
  'dist_powerup': 0,
  'funcao': 'atacar_e_desviar',
  'mais_de_um_jogador_perto': 0,
  'neutro': 0,
  'oportunidade': 0,
  'perigo': 1,
  'player_com_powerup': 1,
  'powerup_existe': 0},
 {'bomba_existe': 0,
  'bomba_player': 0,
  'dist_bomba1': 0,
  'dist_bomba2': 0,
  'dist_bomba3': 0,
  'dist_bomba4': 0,
  'dist_jogador1': 0,
  'dist_jogador2': 5,
  'dist_jogador3': 9,
  'dist_jogador4': 7,
  'dist_powerup': 0,
  'funcao': 'atacar_e_desviar',
  'mais_de_um_jogador_perto': 0,
  'neutro': 0,
  'oportunidade': 0,
  'perigo': 1,
  'player_com_powerup': 1,
  'powerup_existe': 0},
 {'bomba_existe': 0,
  'bomba_player': 0,
  'dist_bomba1': 0,
  'dist_bomba2': 0,
  'dist_bomba3': 0,
  'dist_bomba4': 0,
  'dist_jogador1': 0,
  'dist_jogador2': 7,
  'dist_jogador3': 9,
  'dist_jogador4': 9,
  'dist_powerup': 10,
  'funcao': 'atacar_e_desviar',
  'mais_de_um_jogador_perto': 0,
  'neutro': 0,
  'oportunidade': 0,
  'perigo': 1,
  'player_com_powerup': 0,
  'powerup_existe': 1},
 {'bomba_existe': 0,
  'bomba_player': 0,
  'dist_bomba1': 0,
  'dist_bomba2': 0,
  'dist_bomba3': 0,
  'dist_bomba4': 0,
  'dist_jogador1': 0,
  'dist_jogador2': 11,
  'dist_jogador3': 6,
  'dist_jogador4': 2,
  'dist_powerup': 0,
  'funcao': 'atacar_e_desviar',
  'mais_de_um_jogador_perto': 0,
  'neutro': 0,
  'oportunidade': 0,
  'perigo': 1,
  'player_com_powerup': 1,
  'powerup_existe': 0},
 {'bomba_existe': 0,
  'bomba_player': 0,
  'dist_bomba1': 0,
  'dist_bomba2': 0,
  'dist_bomba3': 0,
  'dist_bomba4': 0,
  'dist_jogador1': 0,
  'dist_jogador2': 1,
  'dist_jogador3': 11,
  'dist_jogador4': 9,
  'dist_powerup': 10,
  'funcao': 'atacar_e_desviar',
  'mais_de_um_jogador_perto': 0,
  'neutro': 0,
  'oportunidade': 0,
  'perigo': 1,
  'player_com_powerup': 0,
  'powerup_existe': 1},
 {'bomba_existe': 0,
  'bomba_player': 0,
  'dist_bomba1': 0,
  'dist_bomba2': 0,
  'dist_bomba3': 0,
  'dist_bomba4': 0,
  'dist_jogador1': 0,
  'dist_jogador2': 8,
  'dist_jogador3': 4,
  'dist_jogador4': 8,
  'dist_powerup': 0,
  'funcao': 'atacar_e_desviar',
  'mais_de_um_jogador_perto': 0,
  'neutro': 0,
  'oportunidade': 0,
  'perigo': 1,
  'player_com_powerup': 1,
  'powerup_existe': 0},
 {'bomba_existe': 0,
  'bomba_player': 0,
  'dist_bomba1': 0,
  'dist_bomba2': 0,
  'dist_bomba3': 0,
  'dist_bomba4': 0,
  'dist_jogador1': 0,
  'dist_jogador2': 9,
  'dist_jogador3': 9,
  'dist_jogador4': 2,
  'dist_powerup': 0,
  'funcao': 'atacar_e_desviar',
  'mais_de_um_jogador_perto': 0,
  'neutro': 0,
  'oportunidade': 0,
  'perigo': 1,
  'player_com_powerup': 0,
  'powerup_existe': 0},
 {'bomba_existe': 0,
  'bomba_player': 0,
  'dist_bomba1': 0,
  'dist_bomba2': 0,
  'dist_bomba3': 0,
  'dist_bomba4': 0,
  'dist_jogador1': 0,
  'dist_jogador2': 12,
  'dist_jogador3': 9,
  'dist_jogador4': 11,
  'dist_powerup': 12,
  'funcao': 'atacar_e_desviar',
  'mais_de_um_jogador_perto': 0,
  'neutro': 0,
  'oportunidade': 0,
  'perigo': 1,
  'player_com_powerup': 1,
  'powerup_existe': 1},
 {'bomba_existe': 0,
  'bomba_player': 0,
  'dist_bomba1': 0,
  'dist_bomba2': 0,
  'dist_bomba3': 0,
  'dist_bomba4': 0,
  'dist_jogador1': 0,
  'dist_jogador2': 7,
  'dist_jogador3': 2,
  'dist_jogador4': 7,
  'dist_powerup': 0,
  'funcao': 'atacar_e_desviar',
  'mais_de_um_jogador_perto': 0,
  'neutro': 0,
  'oportunidade': 0,
  'perigo': 1,
  'player_com_powerup': 1,
  'powerup_existe': 0},
 {'bomba_existe': 0,
  'bomba_player': 0,
  'dist_bomba1': 0,
  'dist_bomba2': 0,
  'dist_bomba3': 0,
  'dist_bomba4': 0,
  'dist_jogador1': 0,
  'dist_jogador2': 10,
  'dist_jogador3': 9,
  'dist_jogador4': 10,
  'dist_powerup': 0,
  'funcao': 'atacar_e_desviar',
  'mais_de_um_jogador_perto': 0,
  'neutro': 0,
  'oportunidade': 0,
  'perigo': 1,
  'player_com_powerup': 1,
  'powerup_existe': 0},
  {'bomba_existe': 0,
  'bomba_player': 0,
  'dist_bomba1': 0,
  'dist_bomba2': 0,
  'dist_bomba3': 0,
  'dist_bomba4': 0,
  'dist_jogador1': 0,
  'dist_jogador2': 14,
  'dist_jogador3': 24,
  'dist_jogador4': 21,
  'dist_powerup': 2,
  'funcao': 'pegar_powerUp',
  'mais_de_um_jogador_perto': 0,
  'neutro': 0,
  'oportunidade': 1,
  'perigo': 0,
  'player_com_powerup': 0,
  'powerup_existe': 1},
 {'bomba_existe': 0,
  'bomba_player': 0,
  'dist_bomba1': 0,
  'dist_bomba2': 0,
  'dist_bomba3': 0,
  'dist_bomba4': 0,
  'dist_jogador1': 0,
  'dist_jogador2': 13,
  'dist_jogador3': 15,
  'dist_jogador4': 20,
  'dist_powerup': 6,
  'funcao': 'pegar_powerUp',
  'mais_de_um_jogador_perto': 0,
  'neutro': 0,
  'oportunidade': 1,
  'perigo': 0,
  'player_com_powerup': 1,
  'powerup_existe': 1},
 {'bomba_existe': 0,
  'bomba_player': 0,
  'dist_bomba1': 0,
  'dist_bomba2': 0,
  'dist_bomba3': 0,
  'dist_bomba4': 0,
  'dist_jogador1': 0,
  'dist_jogador2': 19,
  'dist_jogador3': 23,
  'dist_jogador4': 19,
  'dist_powerup': 5,
  'funcao': 'pegar_powerUp',
  'mais_de_um_jogador_perto': 0,
  'neutro': 0,
  'oportunidade': 1,
  'perigo': 0,
  'player_com_powerup': 0,
  'powerup_existe': 1},
 {'bomba_existe': 0,
  'bomba_player': 0,
  'dist_bomba1': 0,
  'dist_bomba2': 0,
  'dist_bomba3': 0,
  'dist_bomba4': 0,
  'dist_jogador1': 0,
  'dist_jogador2': 13,
  'dist_jogador3': 13,
  'dist_jogador4': 24,
  'dist_powerup': 10,
  'funcao': 'pegar_powerUp',
  'mais_de_um_jogador_perto': 0,
  'neutro': 0,
  'oportunidade': 1,
  'perigo': 0,
  'player_com_powerup': 0,
  'powerup_existe': 1},
 {'bomba_existe': 0,
  'bomba_player': 0,
  'dist_bomba1': 0,
  'dist_bomba2': 0,
  'dist_bomba3': 0,
  'dist_bomba4': 0,
  'dist_jogador1': 0,
  'dist_jogador2': 24,
  'dist_jogador3': 13,
  'dist_jogador4': 17,
  'dist_powerup': 9,
  'funcao': 'pegar_powerUp',
  'mais_de_um_jogador_perto': 0,
  'neutro': 0,
  'oportunidade': 1,
  'perigo': 0,
  'player_com_powerup': 1,
  'powerup_existe': 1},
 {'bomba_existe': 0,
  'bomba_player': 0,
  'dist_bomba1': 0,
  'dist_bomba2': 0,
  'dist_bomba3': 0,
  'dist_bomba4': 0,
  'dist_jogador1': 0,
  'dist_jogador2': 24,
  'dist_jogador3': 16,
  'dist_jogador4': 17,
  'dist_powerup': 4,
  'funcao': 'pegar_powerUp',
  'mais_de_um_jogador_perto': 0,
  'neutro': 0,
  'oportunidade': 1,
  'perigo': 0,
  'player_com_powerup': 1,
  'powerup_existe': 1},
 {'bomba_existe': 0,
  'bomba_player': 0,
  'dist_bomba1': 0,
  'dist_bomba2': 0,
  'dist_bomba3': 0,
  'dist_bomba4': 0,
  'dist_jogador1': 0,
  'dist_jogador2': 20,
  'dist_jogador3': 19,
  'dist_jogador4': 14,
  'dist_powerup': 8,
  'funcao': 'pegar_powerUp',
  'mais_de_um_jogador_perto': 0,
  'neutro': 0,
  'oportunidade': 1,
  'perigo': 0,
  'player_com_powerup': 1,
  'powerup_existe': 1},
 {'bomba_existe': 0,
  'bomba_player': 0,
  'dist_bomba1': 0,
  'dist_bomba2': 0,
  'dist_bomba3': 0,
  'dist_bomba4': 0,
  'dist_jogador1': 0,
  'dist_jogador2': 17,
  'dist_jogador3': 19,
  'dist_jogador4': 23,
  'dist_powerup': 7,
  'funcao': 'pegar_powerUp',
  'mais_de_um_jogador_perto': 0,
  'neutro': 0,
  'oportunidade': 1,
  'perigo': 0,
  'player_com_powerup': 1,
  'powerup_existe': 1},
 {'bomba_existe': 0,
  'bomba_player': 0,
  'dist_bomba1': 0,
  'dist_bomba2': 0,
  'dist_bomba3': 0,
  'dist_bomba4': 0,
  'dist_jogador1': 0,
  'dist_jogador2': 19,
  'dist_jogador3': 14,
  'dist_jogador4': 16,
  'dist_powerup': 8,
  'funcao': 'pegar_powerUp',
  'mais_de_um_jogador_perto': 0,
  'neutro': 0,
  'oportunidade': 1,
  'perigo': 0,
  'player_com_powerup': 0,
  'powerup_existe': 1},
 {'bomba_existe': 0,
  'bomba_player': 0,
  'dist_bomba1': 0,
  'dist_bomba2': 0,
  'dist_bomba3': 0,
  'dist_bomba4': 0,
  'dist_jogador1': 0,
  'dist_jogador2': 18,
  'dist_jogador3': 18,
  'dist_jogador4': 17,
  'dist_powerup': 12,
  'funcao': 'pegar_powerUp',
  'mais_de_um_jogador_perto': 0,
  'neutro': 0,
  'oportunidade': 1,
  'perigo': 0,
  'player_com_powerup': 0,
  'powerup_existe': 1},
 {'bomba_existe': 0,
  'bomba_player': 0,
  'dist_bomba1': 0,
  'dist_bomba2': 0,
  'dist_bomba3': 0,
  'dist_bomba4': 0,
  'dist_jogador1': 0,
  'dist_jogador2': 18,
  'dist_jogador3': 20,
  'dist_jogador4': 22,
  'dist_powerup': 3,
  'funcao': 'pegar_powerUp',
  'mais_de_um_jogador_perto': 0,
  'neutro': 0,
  'oportunidade': 1,
  'perigo': 0,
  'player_com_powerup': 1,
  'powerup_existe': 1},
 {'bomba_existe': 0,
  'bomba_player': 0,
  'dist_bomba1': 0,
  'dist_bomba2': 0,
  'dist_bomba3': 0,
  'dist_bomba4': 0,
  'dist_jogador1': 0,
  'dist_jogador2': 17,
  'dist_jogador3': 19,
  'dist_jogador4': 16,
  'dist_powerup': 12,
  'funcao': 'pegar_powerUp',
  'mais_de_um_jogador_perto': 0,
  'neutro': 0,
  'oportunidade': 1,
  'perigo': 0,
  'player_com_powerup': 0,
  'powerup_existe': 1},
 {'bomba_existe': 0,
  'bomba_player': 0,
  'dist_bomba1': 0,
  'dist_bomba2': 0,
  'dist_bomba3': 0,
  'dist_bomba4': 0,
  'dist_jogador1': 0,
  'dist_jogador2': 19,
  'dist_jogador3': 13,
  'dist_jogador4': 21,
  'dist_powerup': 12,
  'funcao': 'pegar_powerUp',
  'mais_de_um_jogador_perto': 0,
  'neutro': 0,
  'oportunidade': 1,
  'perigo': 0,
  'player_com_powerup': 1,
  'powerup_existe': 1},
 {'bomba_existe': 0,
  'bomba_player': 0,
  'dist_bomba1': 0,
  'dist_bomba2': 0,
  'dist_bomba3': 0,
  'dist_bomba4': 0,
  'dist_jogador1': 0,
  'dist_jogador2': 23,
  'dist_jogador3': 21,
  'dist_jogador4': 17,
  'dist_powerup': 5,
  'funcao': 'pegar_powerUp',
  'mais_de_um_jogador_perto': 0,
  'neutro': 0,
  'oportunidade': 1,
  'perigo': 0,
  'player_com_powerup': 0,
  'powerup_existe': 1},
 {'bomba_existe': 0,
  'bomba_player': 0,
  'dist_bomba1': 0,
  'dist_bomba2': 0,
  'dist_bomba3': 0,
  'dist_bomba4': 0,
  'dist_jogador1': 0,
  'dist_jogador2': 17,
  'dist_jogador3': 19,
  'dist_jogador4': 16,
  'dist_powerup': 4,
  'funcao': 'pegar_powerUp',
  'mais_de_um_jogador_perto': 0,
  'neutro': 0,
  'oportunidade': 1,
  'perigo': 0,
  'player_com_powerup': 1,
  'powerup_existe': 1},
 {'bomba_existe': 0,
  'bomba_player': 0,
  'dist_bomba1': 0,
  'dist_bomba2': 0,
  'dist_bomba3': 0,
  'dist_bomba4': 0,
  'dist_jogador1': 0,
  'dist_jogador2': 21,
  'dist_jogador3': 16,
  'dist_jogador4': 15,
  'dist_powerup': 7,
  'funcao': 'pegar_powerUp',
  'mais_de_um_jogador_perto': 0,
  'neutro': 0,
  'oportunidade': 1,
  'perigo': 0,
  'player_com_powerup': 1,
  'powerup_existe': 1},
 {'bomba_existe': 0,
  'bomba_player': 0,
  'dist_bomba1': 0,
  'dist_bomba2': 0,
  'dist_bomba3': 0,
  'dist_bomba4': 0,
  'dist_jogador1': 0,
  'dist_jogador2': 19,
  'dist_jogador3': 14,
  'dist_jogador4': 20,
  'dist_powerup': 5,
  'funcao': 'pegar_powerUp',
  'mais_de_um_jogador_perto': 0,
  'neutro': 0,
  'oportunidade': 1,
  'perigo': 0,
  'player_com_powerup': 0,
  'powerup_existe': 1},
 {'bomba_existe': 0,
  'bomba_player': 0,
  'dist_bomba1': 0,
  'dist_bomba2': 0,
  'dist_bomba3': 0,
  'dist_bomba4': 0,
  'dist_jogador1': 0,
  'dist_jogador2': 13,
  'dist_jogador3': 15,
  'dist_jogador4': 16,
  'dist_powerup': 11,
  'funcao': 'pegar_powerUp',
  'mais_de_um_jogador_perto': 0,
  'neutro': 0,
  'oportunidade': 1,
  'perigo': 0,
  'player_com_powerup': 1,
  'powerup_existe': 1},
 {'bomba_existe': 0,
  'bomba_player': 0,
  'dist_bomba1': 0,
  'dist_bomba2': 0,
  'dist_bomba3': 0,
  'dist_bomba4': 0,
  'dist_jogador1': 0,
  'dist_jogador2': 23,
  'dist_jogador3': 21,
  'dist_jogador4': 21,
  'dist_powerup': 10,
  'funcao': 'pegar_powerUp',
  'mais_de_um_jogador_perto': 0,
  'neutro': 0,
  'oportunidade': 1,
  'perigo': 0,
  'player_com_powerup': 1,
  'powerup_existe': 1},
 {'bomba_existe': 0,
  'bomba_player': 0,
  'dist_bomba1': 0,
  'dist_bomba2': 0,
  'dist_bomba3': 0,
  'dist_bomba4': 0,
  'dist_jogador1': 0,
  'dist_jogador2': 21,
  'dist_jogador3': 22,
  'dist_jogador4': 16,
  'dist_powerup': 2,
  'funcao': 'pegar_powerUp',
  'mais_de_um_jogador_perto': 0,
  'neutro': 0,
  'oportunidade': 1,
  'perigo': 0,
  'player_com_powerup': 0,
  'powerup_existe': 1},
 {'bomba_existe': 0,
  'bomba_player': 0,
  'dist_bomba1': 0,
  'dist_bomba2': 0,
  'dist_bomba3': 0,
  'dist_bomba4': 0,
  'dist_jogador1': 0,
  'dist_jogador2': 23,
  'dist_jogador3': 19,
  'dist_jogador4': 21,
  'dist_powerup': 8,
  'funcao': 'pegar_powerUp',
  'mais_de_um_jogador_perto': 0,
  'neutro': 0,
  'oportunidade': 1,
  'perigo': 0,
  'player_com_powerup': 0,
  'powerup_existe': 1},
 {'bomba_existe': 0,
  'bomba_player': 0,
  'dist_bomba1': 0,
  'dist_bomba2': 0,
  'dist_bomba3': 0,
  'dist_bomba4': 0,
  'dist_jogador1': 0,
  'dist_jogador2': 21,
  'dist_jogador3': 14,
  'dist_jogador4': 21,
  'dist_powerup': 1,
  'funcao': 'pegar_powerUp',
  'mais_de_um_jogador_perto': 0,
  'neutro': 0,
  'oportunidade': 1,
  'perigo': 0,
  'player_com_powerup': 0,
  'powerup_existe': 1},
 {'bomba_existe': 0,
  'bomba_player': 0,
  'dist_bomba1': 0,
  'dist_bomba2': 0,
  'dist_bomba3': 0,
  'dist_bomba4': 0,
  'dist_jogador1': 0,
  'dist_jogador2': 24,
  'dist_jogador3': 23,
  'dist_jogador4': 23,
  'dist_powerup': 10,
  'funcao': 'pegar_powerUp',
  'mais_de_um_jogador_perto': 0,
  'neutro': 0,
  'oportunidade': 1,
  'perigo': 0,
  'player_com_powerup': 0,
  'powerup_existe': 1},
 {'bomba_existe': 1,
  'bomba_player': 0,
  'dist_bomba1': 0,
  'dist_bomba2': 22,
  'dist_bomba3': 20,
  'dist_bomba4': 15,
  'dist_jogador1': 0,
  'dist_jogador2': 21,
  'dist_jogador3': 18,
  'dist_jogador4': 14,
  'dist_powerup': 6,
  'funcao': 'pegar_powerUp',
  'mais_de_um_jogador_perto': 0,
  'neutro': 0,
  'oportunidade': 1,
  'perigo': 0,
  'player_com_powerup': 1,
  'powerup_existe': 1},
 {'bomba_existe': 1,
  'bomba_player': 0,
  'dist_bomba1': 0,
  'dist_bomba2': 18,
  'dist_bomba3': 15,
  'dist_bomba4': 23,
  'dist_jogador1': 0,
  'dist_jogador2': 19,
  'dist_jogador3': 17,
  'dist_jogador4': 21,
  'dist_powerup': 7,
  'funcao': 'pegar_powerUp',
  'mais_de_um_jogador_perto': 0,
  'neutro': 0,
  'oportunidade': 1,
  'perigo': 0,
  'player_com_powerup': 0,
  'powerup_existe': 1},
 {'bomba_existe': 1,
  'bomba_player': 0,
  'dist_bomba1': 0,
  'dist_bomba2': 15,
  'dist_bomba3': 19,
  'dist_bomba4': 20,
  'dist_jogador1': 0,
  'dist_jogador2': 16,
  'dist_jogador3': 17,
  'dist_jogador4': 21,
  'dist_powerup': 10,
  'funcao': 'pegar_powerUp',
  'mais_de_um_jogador_perto': 0,
  'neutro': 0,
  'oportunidade': 1,
  'perigo': 0,
  'player_com_powerup': 0,
  'powerup_existe': 1},
 {'bomba_existe': 1,
  'bomba_player': 0,
  'dist_bomba1': 0,
  'dist_bomba2': 23,
  'dist_bomba3': 17,
  'dist_bomba4': 14,
  'dist_jogador1': 0,
  'dist_jogador2': 22,
  'dist_jogador3': 19,
  'dist_jogador4': 14,
  'dist_powerup': 7,
  'funcao': 'pegar_powerUp',
  'mais_de_um_jogador_perto': 0,
  'neutro': 0,
  'oportunidade': 1,
  'perigo': 0,
  'player_com_powerup': 0,
  'powerup_existe': 1},
 {'bomba_existe': 1,
  'bomba_player': 0,
  'dist_bomba1': 0,
  'dist_bomba2': 21,
  'dist_bomba3': 18,
  'dist_bomba4': 13,
  'dist_jogador1': 0,
  'dist_jogador2': 22,
  'dist_jogador3': 16,
  'dist_jogador4': 15,
  'dist_powerup': 8,
  'funcao': 'pegar_powerUp',
  'mais_de_um_jogador_perto': 0,
  'neutro': 0,
  'oportunidade': 1,
  'perigo': 0,
  'player_com_powerup': 0,
  'powerup_existe': 1},
 {'bomba_existe': 1,
  'bomba_player': 0,
  'dist_bomba1': 0,
  'dist_bomba2': 19,
  'dist_bomba3': 17,
  'dist_bomba4': 17,
  'dist_jogador1': 0,
  'dist_jogador2': 18,
  'dist_jogador3': 17,
  'dist_jogador4': 16,
  'dist_powerup': 8,
  'funcao': 'pegar_powerUp',
  'mais_de_um_jogador_perto': 0,
  'neutro': 0,
  'oportunidade': 1,
  'perigo': 0,
  'player_com_powerup': 0,
  'powerup_existe': 1},
 {'bomba_existe': 1,
  'bomba_player': 0,
  'dist_bomba1': 0,
  'dist_bomba2': 17,
  'dist_bomba3': 18,
  'dist_bomba4': 14,
  'dist_jogador1': 0,
  'dist_jogador2': 18,
  'dist_jogador3': 17,
  'dist_jogador4': 16,
  'dist_powerup': 5,
  'funcao': 'pegar_powerUp',
  'mais_de_um_jogador_perto': 0,
  'neutro': 0,
  'oportunidade': 1,
  'perigo': 0,
  'player_com_powerup': 0,
  'powerup_existe': 1},
 {'bomba_existe': 1,
  'bomba_player': 0,
  'dist_bomba1': 0,
  'dist_bomba2': 16,
  'dist_bomba3': 16,
  'dist_bomba4': 17,
  'dist_jogador1': 0,
  'dist_jogador2': 14,
  'dist_jogador3': 17,
  'dist_jogador4': 15,
  'dist_powerup': 1,
  'funcao': 'pegar_powerUp',
  'mais_de_um_jogador_perto': 0,
  'neutro': 0,
  'oportunidade': 1,
  'perigo': 0,
  'player_com_powerup': 1,
  'powerup_existe': 1},
 {'bomba_existe': 1,
  'bomba_player': 0,
  'dist_bomba1': 0,
  'dist_bomba2': 24,
  'dist_bomba3': 21,
  'dist_bomba4': 14,
  'dist_jogador1': 0,
  'dist_jogador2': 24,
  'dist_jogador3': 19,
  'dist_jogador4': 16,
  'dist_powerup': 10,
  'funcao': 'pegar_powerUp',
  'mais_de_um_jogador_perto': 0,
  'neutro': 0,
  'oportunidade': 1,
  'perigo': 0,
  'player_com_powerup': 1,
  'powerup_existe': 1},
 {'bomba_existe': 1,
  'bomba_player': 0,
  'dist_bomba1': 0,
  'dist_bomba2': 24,
  'dist_bomba3': 20,
  'dist_bomba4': 19,
  'dist_jogador1': 0,
  'dist_jogador2': 24,
  'dist_jogador3': 19,
  'dist_jogador4': 19,
  'dist_powerup': 12,
  'funcao': 'pegar_powerUp',
  'mais_de_um_jogador_perto': 0,
  'neutro': 0,
  'oportunidade': 1,
  'perigo': 0,
  'player_com_powerup': 1,
  'powerup_existe': 1},
 {'bomba_existe': 1,
  'bomba_player': 0,
  'dist_bomba1': 0,
  'dist_bomba2': 16,
  'dist_bomba3': 20,
  'dist_bomba4': 18,
  'dist_jogador1': 0,
  'dist_jogador2': 18,
  'dist_jogador3': 21,
  'dist_jogador4': 18,
  'dist_powerup': 4,
  'funcao': 'pegar_powerUp',
  'mais_de_um_jogador_perto': 0,
  'neutro': 0,
  'oportunidade': 1,
  'perigo': 0,
  'player_com_powerup': 1,
  'powerup_existe': 1},
 {'bomba_existe': 1,
  'bomba_player': 0,
  'dist_bomba1': 0,
  'dist_bomba2': 16,
  'dist_bomba3': 18,
  'dist_bomba4': 21,
  'dist_jogador1': 0,
  'dist_jogador2': 16,
  'dist_jogador3': 19,
  'dist_jogador4': 23,
  'dist_powerup': 10,
  'funcao': 'pegar_powerUp',
  'mais_de_um_jogador_perto': 0,
  'neutro': 0,
  'oportunidade': 1,
  'perigo': 0,
  'player_com_powerup': 0,
  'powerup_existe': 1},
 {'bomba_existe': 1,
  'bomba_player': 0,
  'dist_bomba1': 0,
  'dist_bomba2': 14,
  'dist_bomba3': 20,
  'dist_bomba4': 19,
  'dist_jogador1': 0,
  'dist_jogador2': 14,
  'dist_jogador3': 20,
  'dist_jogador4': 19,
  'dist_powerup': 9,
  'funcao': 'pegar_powerUp',
  'mais_de_um_jogador_perto': 0,
  'neutro': 0,
  'oportunidade': 1,
  'perigo': 0,
  'player_com_powerup': 0,
  'powerup_existe': 1},
 {'bomba_existe': 1,
  'bomba_player': 0,
  'dist_bomba1': 0,
  'dist_bomba2': 20,
  'dist_bomba3': 13,
  'dist_bomba4': 15,
  'dist_jogador1': 0,
  'dist_jogador2': 19,
  'dist_jogador3': 14,
  'dist_jogador4': 14,
  'dist_powerup': 8,
  'funcao': 'pegar_powerUp',
  'mais_de_um_jogador_perto': 0,
  'neutro': 0,
  'oportunidade': 1,
  'perigo': 0,
  'player_com_powerup': 0,
  'powerup_existe': 1},
 {'bomba_existe': 1,
  'bomba_player': 0,
  'dist_bomba1': 0,
  'dist_bomba2': 17,
  'dist_bomba3': 24,
  'dist_bomba4': 20,
  'dist_jogador1': 0,
  'dist_jogador2': 16,
  'dist_jogador3': 23,
  'dist_jogador4': 22,
  'dist_powerup': 5,
  'funcao': 'pegar_powerUp',
  'mais_de_um_jogador_perto': 0,
  'neutro': 0,
  'oportunidade': 1,
  'perigo': 0,
  'player_com_powerup': 0,
  'powerup_existe': 1},
 {'bomba_existe': 1,
  'bomba_player': 0,
  'dist_bomba1': 0,
  'dist_bomba2': 24,
  'dist_bomba3': 22,
  'dist_bomba4': 16,
  'dist_jogador1': 0,
  'dist_jogador2': 24,
  'dist_jogador3': 20,
  'dist_jogador4': 15,
  'dist_powerup': 8,
  'funcao': 'pegar_powerUp',
  'mais_de_um_jogador_perto': 0,
  'neutro': 0,
  'oportunidade': 1,
  'perigo': 0,
  'player_com_powerup': 0,
  'powerup_existe': 1},
 {'bomba_existe': 1,
  'bomba_player': 0,
  'dist_bomba1': 0,
  'dist_bomba2': 15,
  'dist_bomba3': 24,
  'dist_bomba4': 22,
  'dist_jogador1': 0,
  'dist_jogador2': 13,
  'dist_jogador3': 23,
  'dist_jogador4': 21,
  'dist_powerup': 2,
  'funcao': 'pegar_powerUp',
  'mais_de_um_jogador_perto': 0,
  'neutro': 0,
  'oportunidade': 1,
  'perigo': 0,
  'player_com_powerup': 1,
  'powerup_existe': 1},
 {'bomba_existe': 1,
  'bomba_player': 0,
  'dist_bomba1': 0,
  'dist_bomba2': 17,
  'dist_bomba3': 15,
  'dist_bomba4': 20,
  'dist_jogador1': 0,
  'dist_jogador2': 17,
  'dist_jogador3': 13,
  'dist_jogador4': 21,
  'dist_powerup': 12,
  'funcao': 'pegar_powerUp',
  'mais_de_um_jogador_perto': 0,
  'neutro': 0,
  'oportunidade': 1,
  'perigo': 0,
  'player_com_powerup': 1,
  'powerup_existe': 1},
 {'bomba_existe': 1,
  'bomba_player': 0,
  'dist_bomba1': 0,
  'dist_bomba2': 16,
  'dist_bomba3': 18,
  'dist_bomba4': 17,
  'dist_jogador1': 0,
  'dist_jogador2': 14,
  'dist_jogador3': 16,
  'dist_jogador4': 15,
  'dist_powerup': 3,
  'funcao': 'pegar_powerUp',
  'mais_de_um_jogador_perto': 0,
  'neutro': 0,
  'oportunidade': 1,
  'perigo': 0,
  'player_com_powerup': 0,
  'powerup_existe': 1},
 {'bomba_existe': 1,
  'bomba_player': 0,
  'dist_bomba1': 0,
  'dist_bomba2': 13,
  'dist_bomba3': 20,
  'dist_bomba4': 13,
  'dist_jogador1': 0,
  'dist_jogador2': 15,
  'dist_jogador3': 20,
  'dist_jogador4': 15,
  'dist_powerup': 12,
  'funcao': 'pegar_powerUp',
  'mais_de_um_jogador_perto': 0,
  'neutro': 0,
  'oportunidade': 1,
  'perigo': 0,
  'player_com_powerup': 0,
  'powerup_existe': 1},
 {'bomba_existe': 1,
  'bomba_player': 0,
  'dist_bomba1': 0,
  'dist_bomba2': 20,
  'dist_bomba3': 20,
  'dist_bomba4': 13,
  'dist_jogador1': 0,
  'dist_jogador2': 20,
  'dist_jogador3': 18,
  'dist_jogador4': 15,
  'dist_powerup': 6,
  'funcao': 'pegar_powerUp',
  'mais_de_um_jogador_perto': 0,
  'neutro': 0,
  'oportunidade': 1,
  'perigo': 0,
  'player_com_powerup': 0,
  'powerup_existe': 1},
 {'bomba_existe': 1,
  'bomba_player': 0,
  'dist_bomba1': 0,
  'dist_bomba2': 21,
  'dist_bomba3': 18,
  'dist_bomba4': 18,
  'dist_jogador1': 0,
  'dist_jogador2': 22,
  'dist_jogador3': 17,
  'dist_jogador4': 19,
  'dist_powerup': 9,
  'funcao': 'pegar_powerUp',
  'mais_de_um_jogador_perto': 0,
  'neutro': 0,
  'oportunidade': 1,
  'perigo': 0,
  'player_com_powerup': 1,
  'powerup_existe': 1},
 {'bomba_existe': 1,
  'bomba_player': 0,
  'dist_bomba1': 0,
  'dist_bomba2': 18,
  'dist_bomba3': 11,
  'dist_bomba4': 19,
  'dist_jogador1': 0,
  'dist_jogador2': 20,
  'dist_jogador3': 13,
  'dist_jogador4': 20,
  'dist_powerup': 10,
  'funcao': 'pegar_powerUp',
  'mais_de_um_jogador_perto': 0,
  'neutro': 0,
  'oportunidade': 1,
  'perigo': 0,
  'player_com_powerup': 1,
  'powerup_existe': 1},
 {'bomba_existe': 1,
  'bomba_player': 0,
  'dist_bomba1': 0,
  'dist_bomba2': 16,
  'dist_bomba3': 18,
  'dist_bomba4': 20,
  'dist_jogador1': 0,
  'dist_jogador2': 17,
  'dist_jogador3': 16,
  'dist_jogador4': 22,
  'dist_powerup': 8,
  'funcao': 'pegar_powerUp',
  'mais_de_um_jogador_perto': 0,
  'neutro': 0,
  'oportunidade': 1,
  'perigo': 0,
  'player_com_powerup': 1,
  'powerup_existe': 1},
 {'bomba_existe': 1,
  'bomba_player': 0,
  'dist_bomba1': 0,
  'dist_bomba2': 23,
  'dist_bomba3': 22,
  'dist_bomba4': 22,
  'dist_jogador1': 0,
  'dist_jogador2': 23,
  'dist_jogador3': 23,
  'dist_jogador4': 23,
  'dist_powerup': 0,
  'funcao': 'passear_pelo_mapa',
  'mais_de_um_jogador_perto': 0,
  'neutro': 1,
  'oportunidade': 0,
  'perigo': 0,
  'player_com_powerup': 0,
  'powerup_existe': 0},
 {'bomba_existe': 1,
  'bomba_player': 0,
  'dist_bomba1': 0,
  'dist_bomba2': 24,
  'dist_bomba3': 19,
  'dist_bomba4': 24,
  'dist_jogador1': 0,
  'dist_jogador2': 23,
  'dist_jogador3': 17,
  'dist_jogador4': 23,
  'dist_powerup': 0,
  'funcao': 'passear_pelo_mapa',
  'mais_de_um_jogador_perto': 0,
  'neutro': 1,
  'oportunidade': 0,
  'perigo': 0,
  'player_com_powerup': 0,
  'powerup_existe': 0},
 {'bomba_existe': 1,
  'bomba_player': 0,
  'dist_bomba1': 0,
  'dist_bomba2': 15,
  'dist_bomba3': 22,
  'dist_bomba4': 24,
  'dist_jogador1': 0,
  'dist_jogador2': 14,
  'dist_jogador3': 22,
  'dist_jogador4': 23,
  'dist_powerup': 0,
  'funcao': 'passear_pelo_mapa',
  'mais_de_um_jogador_perto': 0,
  'neutro': 1,
  'oportunidade': 0,
  'perigo': 0,
  'player_com_powerup': 0,
  'powerup_existe': 0},
 {'bomba_existe': 1,
  'bomba_player': 0,
  'dist_bomba1': 0,
  'dist_bomba2': 19,
  'dist_bomba3': 18,
  'dist_bomba4': 16,
  'dist_jogador1': 0,
  'dist_jogador2': 19,
  'dist_jogador3': 18,
  'dist_jogador4': 15,
  'dist_powerup': 0,
  'funcao': 'passear_pelo_mapa',
  'mais_de_um_jogador_perto': 0,
  'neutro': 1,
  'oportunidade': 0,
  'perigo': 0,
  'player_com_powerup': 1,
  'powerup_existe': 0},
 {'bomba_existe': 1,
  'bomba_player': 0,
  'dist_bomba1': 0,
  'dist_bomba2': 15,
  'dist_bomba3': 16,
  'dist_bomba4': 24,
  'dist_jogador1': 0,
  'dist_jogador2': 16,
  'dist_jogador3': 16,
  'dist_jogador4': 24,
  'dist_powerup': 0,
  'funcao': 'passear_pelo_mapa',
  'mais_de_um_jogador_perto': 0,
  'neutro': 1,
  'oportunidade': 0,
  'perigo': 0,
  'player_com_powerup': 1,
  'powerup_existe': 0},
 {'bomba_existe': 1,
  'bomba_player': 0,
  'dist_bomba1': 0,
  'dist_bomba2': 22,
  'dist_bomba3': 16,
  'dist_bomba4': 21,
  'dist_jogador1': 0,
  'dist_jogador2': 24,
  'dist_jogador3': 14,
  'dist_jogador4': 21,
  'dist_powerup': 0,
  'funcao': 'passear_pelo_mapa',
  'mais_de_um_jogador_perto': 0,
  'neutro': 1,
  'oportunidade': 0,
  'perigo': 0,
  'player_com_powerup': 1,
  'powerup_existe': 0},
 {'bomba_existe': 1,
  'bomba_player': 0,
  'dist_bomba1': 0,
  'dist_bomba2': 20,
  'dist_bomba3': 22,
  'dist_bomba4': 23,
  'dist_jogador1': 0,
  'dist_jogador2': 22,
  'dist_jogador3': 20,
  'dist_jogador4': 24,
  'dist_powerup': 0,
  'funcao': 'passear_pelo_mapa',
  'mais_de_um_jogador_perto': 0,
  'neutro': 1,
  'oportunidade': 0,
  'perigo': 0,
  'player_com_powerup': 1,
  'powerup_existe': 0},
 {'bomba_existe': 1,
  'bomba_player': 0,
  'dist_bomba1': 0,
  'dist_bomba2': 19,
  'dist_bomba3': 11,
  'dist_bomba4': 21,
  'dist_jogador1': 0,
  'dist_jogador2': 20,
  'dist_jogador3': 13,
  'dist_jogador4': 20,
  'dist_powerup': 0,
  'funcao': 'passear_pelo_mapa',
  'mais_de_um_jogador_perto': 0,
  'neutro': 1,
  'oportunidade': 0,
  'perigo': 0,
  'player_com_powerup': 0,
  'powerup_existe': 0},
 {'bomba_existe': 1,
  'bomba_player': 0,
  'dist_bomba1': 0,
  'dist_bomba2': 12,
  'dist_bomba3': 22,
  'dist_bomba4': 16,
  'dist_jogador1': 0,
  'dist_jogador2': 14,
  'dist_jogador3': 23,
  'dist_jogador4': 17,
  'dist_powerup': 0,
  'funcao': 'passear_pelo_mapa',
  'mais_de_um_jogador_perto': 0,
  'neutro': 1,
  'oportunidade': 0,
  'perigo': 0,
  'player_com_powerup': 1,
  'powerup_existe': 0},
 {'bomba_existe': 1,
  'bomba_player': 0,
  'dist_bomba1': 0,
  'dist_bomba2': 14,
  'dist_bomba3': 20,
  'dist_bomba4': 20,
  'dist_jogador1': 0,
  'dist_jogador2': 13,
  'dist_jogador3': 18,
  'dist_jogador4': 21,
  'dist_powerup': 0,
  'funcao': 'passear_pelo_mapa',
  'mais_de_um_jogador_perto': 0,
  'neutro': 1,
  'oportunidade': 0,
  'perigo': 0,
  'player_com_powerup': 1,
  'powerup_existe': 0},
 {'bomba_existe': 1,
  'bomba_player': 0,
  'dist_bomba1': 0,
  'dist_bomba2': 21,
  'dist_bomba3': 20,
  'dist_bomba4': 18,
  'dist_jogador1': 0,
  'dist_jogador2': 20,
  'dist_jogador3': 21,
  'dist_jogador4': 16,
  'dist_powerup': 0,
  'funcao': 'passear_pelo_mapa',
  'mais_de_um_jogador_perto': 0,
  'neutro': 1,
  'oportunidade': 0,
  'perigo': 0,
  'player_com_powerup': 1,
  'powerup_existe': 0},
 {'bomba_existe': 1,
  'bomba_player': 0,
  'dist_bomba1': 0,
  'dist_bomba2': 13,
  'dist_bomba3': 24,
  'dist_bomba4': 22,
  'dist_jogador1': 0,
  'dist_jogador2': 15,
  'dist_jogador3': 22,
  'dist_jogador4': 23,
  'dist_powerup': 0,
  'funcao': 'passear_pelo_mapa',
  'mais_de_um_jogador_perto': 0,
  'neutro': 1,
  'oportunidade': 0,
  'perigo': 0,
  'player_com_powerup': 1,
  'powerup_existe': 0},
 {'bomba_existe': 1,
  'bomba_player': 0,
  'dist_bomba1': 0,
  'dist_bomba2': 24,
  'dist_bomba3': 21,
  'dist_bomba4': 18,
  'dist_jogador1': 0,
  'dist_jogador2': 23,
  'dist_jogador3': 20,
  'dist_jogador4': 19,
  'dist_powerup': 0,
  'funcao': 'passear_pelo_mapa',
  'mais_de_um_jogador_perto': 0,
  'neutro': 1,
  'oportunidade': 0,
  'perigo': 0,
  'player_com_powerup': 1,
  'powerup_existe': 0},
 {'bomba_existe': 1,
  'bomba_player': 0,
  'dist_bomba1': 0,
  'dist_bomba2': 16,
  'dist_bomba3': 24,
  'dist_bomba4': 17,
  'dist_jogador1': 0,
  'dist_jogador2': 14,
  'dist_jogador3': 23,
  'dist_jogador4': 18,
  'dist_powerup': 0,
  'funcao': 'passear_pelo_mapa',
  'mais_de_um_jogador_perto': 0,
  'neutro': 1,
  'oportunidade': 0,
  'perigo': 0,
  'player_com_powerup': 0,
  'powerup_existe': 0},
 {'bomba_existe': 1,
  'bomba_player': 0,
  'dist_bomba1': 0,
  'dist_bomba2': 24,
  'dist_bomba3': 23,
  'dist_bomba4': 24,
  'dist_jogador1': 0,
  'dist_jogador2': 24,
  'dist_jogador3': 23,
  'dist_jogador4': 22,
  'dist_powerup': 0,
  'funcao': 'passear_pelo_mapa',
  'mais_de_um_jogador_perto': 0,
  'neutro': 1,
  'oportunidade': 0,
  'perigo': 0,
  'player_com_powerup': 1,
  'powerup_existe': 0},
 {'bomba_existe': 1,
  'bomba_player': 0,
  'dist_bomba1': 0,
  'dist_bomba2': 21,
  'dist_bomba3': 21,
  'dist_bomba4': 20,
  'dist_jogador1': 0,
  'dist_jogador2': 22,
  'dist_jogador3': 22,
  'dist_jogador4': 21,
  'dist_powerup': 0,
  'funcao': 'passear_pelo_mapa',
  'mais_de_um_jogador_perto': 0,
  'neutro': 1,
  'oportunidade': 0,
  'perigo': 0,
  'player_com_powerup': 1,
  'powerup_existe': 0},
 {'bomba_existe': 1,
  'bomba_player': 0,
  'dist_bomba1': 0,
  'dist_bomba2': 23,
  'dist_bomba3': 17,
  'dist_bomba4': 24,
  'dist_jogador1': 0,
  'dist_jogador2': 24,
  'dist_jogador3': 19,
  'dist_jogador4': 24,
  'dist_powerup': 0,
  'funcao': 'passear_pelo_mapa',
  'mais_de_um_jogador_perto': 0,
  'neutro': 1,
  'oportunidade': 0,
  'perigo': 0,
  'player_com_powerup': 1,
  'powerup_existe': 0},
 {'bomba_existe': 1,
  'bomba_player': 0,
  'dist_bomba1': 0,
  'dist_bomba2': 20,
  'dist_bomba3': 22,
  'dist_bomba4': 20,
  'dist_jogador1': 0,
  'dist_jogador2': 18,
  'dist_jogador3': 21,
  'dist_jogador4': 19,
  'dist_powerup': 0,
  'funcao': 'passear_pelo_mapa',
  'mais_de_um_jogador_perto': 0,
  'neutro': 1,
  'oportunidade': 0,
  'perigo': 0,
  'player_com_powerup': 1,
  'powerup_existe': 0},
 {'bomba_existe': 1,
  'bomba_player': 0,
  'dist_bomba1': 0,
  'dist_bomba2': 15,
  'dist_bomba3': 24,
  'dist_bomba4': 18,
  'dist_jogador1': 0,
  'dist_jogador2': 13,
  'dist_jogador3': 24,
  'dist_jogador4': 16,
  'dist_powerup': 0,
  'funcao': 'passear_pelo_mapa',
  'mais_de_um_jogador_perto': 0,
  'neutro': 1,
  'oportunidade': 0,
  'perigo': 0,
  'player_com_powerup': 1,
  'powerup_existe': 0},
 {'bomba_existe': 1,
  'bomba_player': 0,
  'dist_bomba1': 0,
  'dist_bomba2': 13,
  'dist_bomba3': 19,
  'dist_bomba4': 17,
  'dist_jogador1': 0,
  'dist_jogador2': 13,
  'dist_jogador3': 20,
  'dist_jogador4': 19,
  'dist_powerup': 0,
  'funcao': 'passear_pelo_mapa',
  'mais_de_um_jogador_perto': 0,
  'neutro': 1,
  'oportunidade': 0,
  'perigo': 0,
  'player_com_powerup': 1,
  'powerup_existe': 0},
 {'bomba_existe': 0,
  'bomba_player': 0,
  'dist_bomba1': 0,
  'dist_bomba2': 0,
  'dist_bomba3': 0,
  'dist_bomba4': 0,
  'dist_jogador1': 0,
  'dist_jogador2': 14,
  'dist_jogador3': 16,
  'dist_jogador4': 20,
  'dist_powerup': 0,
  'funcao': 'passear_pelo_mapa',
  'mais_de_um_jogador_perto': 0,
  'neutro': 1,
  'oportunidade': 0,
  'perigo': 0,
  'player_com_powerup': 0,
  'powerup_existe': 0},
 {'bomba_existe': 0,
  'bomba_player': 0,
  'dist_bomba1': 0,
  'dist_bomba2': 0,
  'dist_bomba3': 0,
  'dist_bomba4': 0,
  'dist_jogador1': 0,
  'dist_jogador2': 15,
  'dist_jogador3': 20,
  'dist_jogador4': 21,
  'dist_powerup': 0,
  'funcao': 'passear_pelo_mapa',
  'mais_de_um_jogador_perto': 0,
  'neutro': 1,
  'oportunidade': 0,
  'perigo': 0,
  'player_com_powerup': 1,
  'powerup_existe': 0},
 {'bomba_existe': 0,
  'bomba_player': 0,
  'dist_bomba1': 0,
  'dist_bomba2': 0,
  'dist_bomba3': 0,
  'dist_bomba4': 0,
  'dist_jogador1': 0,
  'dist_jogador2': 16,
  'dist_jogador3': 19,
  'dist_jogador4': 16,
  'dist_powerup': 0,
  'funcao': 'passear_pelo_mapa',
  'mais_de_um_jogador_perto': 0,
  'neutro': 1,
  'oportunidade': 0,
  'perigo': 0,
  'player_com_powerup': 0,
  'powerup_existe': 0},
 {'bomba_existe': 0,
  'bomba_player': 0,
  'dist_bomba1': 0,
  'dist_bomba2': 0,
  'dist_bomba3': 0,
  'dist_bomba4': 0,
  'dist_jogador1': 0,
  'dist_jogador2': 19,
  'dist_jogador3': 24,
  'dist_jogador4': 13,
  'dist_powerup': 0,
  'funcao': 'passear_pelo_mapa',
  'mais_de_um_jogador_perto': 0,
  'neutro': 1,
  'oportunidade': 0,
  'perigo': 0,
  'player_com_powerup': 0,
  'powerup_existe': 0},
 {'bomba_existe': 0,
  'bomba_player': 0,
  'dist_bomba1': 0,
  'dist_bomba2': 0,
  'dist_bomba3': 0,
  'dist_bomba4': 0,
  'dist_jogador1': 0,
  'dist_jogador2': 16,
  'dist_jogador3': 23,
  'dist_jogador4': 20,
  'dist_powerup': 0,
  'funcao': 'passear_pelo_mapa',
  'mais_de_um_jogador_perto': 0,
  'neutro': 1,
  'oportunidade': 0,
  'perigo': 0,
  'player_com_powerup': 1,
  'powerup_existe': 0},
 {'bomba_existe': 0,
  'bomba_player': 0,
  'dist_bomba1': 0,
  'dist_bomba2': 0,
  'dist_bomba3': 0,
  'dist_bomba4': 0,
  'dist_jogador1': 0,
  'dist_jogador2': 22,
  'dist_jogador3': 22,
  'dist_jogador4': 17,
  'dist_powerup': 0,
  'funcao': 'passear_pelo_mapa',
  'mais_de_um_jogador_perto': 0,
  'neutro': 1,
  'oportunidade': 0,
  'perigo': 0,
  'player_com_powerup': 0,
  'powerup_existe': 0},
 {'bomba_existe': 0,
  'bomba_player': 0,
  'dist_bomba1': 0,
  'dist_bomba2': 0,
  'dist_bomba3': 0,
  'dist_bomba4': 0,
  'dist_jogador1': 0,
  'dist_jogador2': 13,
  'dist_jogador3': 24,
  'dist_jogador4': 13,
  'dist_powerup': 0,
  'funcao': 'passear_pelo_mapa',
  'mais_de_um_jogador_perto': 0,
  'neutro': 1,
  'oportunidade': 0,
  'perigo': 0,
  'player_com_powerup': 0,
  'powerup_existe': 0},
 {'bomba_existe': 0,
  'bomba_player': 0,
  'dist_bomba1': 0,
  'dist_bomba2': 0,
  'dist_bomba3': 0,
  'dist_bomba4': 0,
  'dist_jogador1': 0,
  'dist_jogador2': 23,
  'dist_jogador3': 24,
  'dist_jogador4': 20,
  'dist_powerup': 0,
  'funcao': 'passear_pelo_mapa',
  'mais_de_um_jogador_perto': 0,
  'neutro': 1,
  'oportunidade': 0,
  'perigo': 0,
  'player_com_powerup': 0,
  'powerup_existe': 0},
 {'bomba_existe': 0,
  'bomba_player': 0,
  'dist_bomba1': 0,
  'dist_bomba2': 0,
  'dist_bomba3': 0,
  'dist_bomba4': 0,
  'dist_jogador1': 0,
  'dist_jogador2': 13,
  'dist_jogador3': 20,
  'dist_jogador4': 24,
  'dist_powerup': 0,
  'funcao': 'passear_pelo_mapa',
  'mais_de_um_jogador_perto': 0,
  'neutro': 1,
  'oportunidade': 0,
  'perigo': 0,
  'player_com_powerup': 0,
  'powerup_existe': 0},
 {'bomba_existe': 0,
  'bomba_player': 0,
  'dist_bomba1': 0,
  'dist_bomba2': 0,
  'dist_bomba3': 0,
  'dist_bomba4': 0,
  'dist_jogador1': 0,
  'dist_jogador2': 23,
  'dist_jogador3': 24,
  'dist_jogador4': 21,
  'dist_powerup': 0,
  'funcao': 'passear_pelo_mapa',
  'mais_de_um_jogador_perto': 0,
  'neutro': 1,
  'oportunidade': 0,
  'perigo': 0,
  'player_com_powerup': 0,
  'powerup_existe': 0},
 {'bomba_existe': 0,
  'bomba_player': 0,
  'dist_bomba1': 0,
  'dist_bomba2': 0,
  'dist_bomba3': 0,
  'dist_bomba4': 0,
  'dist_jogador1': 0,
  'dist_jogador2': 22,
  'dist_jogador3': 17,
  'dist_jogador4': 15,
  'dist_powerup': 0,
  'funcao': 'passear_pelo_mapa',
  'mais_de_um_jogador_perto': 0,
  'neutro': 1,
  'oportunidade': 0,
  'perigo': 0,
  'player_com_powerup': 1,
  'powerup_existe': 0},
 {'bomba_existe': 0,
  'bomba_player': 0,
  'dist_bomba1': 0,
  'dist_bomba2': 0,
  'dist_bomba3': 0,
  'dist_bomba4': 0,
  'dist_jogador1': 0,
  'dist_jogador2': 24,
  'dist_jogador3': 15,
  'dist_jogador4': 21,
  'dist_powerup': 0,
  'funcao': 'passear_pelo_mapa',
  'mais_de_um_jogador_perto': 0,
  'neutro': 1,
  'oportunidade': 0,
  'perigo': 0,
  'player_com_powerup': 1,
  'powerup_existe': 0},
 {'bomba_existe': 0,
  'bomba_player': 0,
  'dist_bomba1': 0,
  'dist_bomba2': 0,
  'dist_bomba3': 0,
  'dist_bomba4': 0,
  'dist_jogador1': 0,
  'dist_jogador2': 24,
  'dist_jogador3': 18,
  'dist_jogador4': 13,
  'dist_powerup': 0,
  'funcao': 'passear_pelo_mapa',
  'mais_de_um_jogador_perto': 0,
  'neutro': 1,
  'oportunidade': 0,
  'perigo': 0,
  'player_com_powerup': 0,
  'powerup_existe': 0},
 {'bomba_existe': 0,
  'bomba_player': 0,
  'dist_bomba1': 0,
  'dist_bomba2': 0,
  'dist_bomba3': 0,
  'dist_bomba4': 0,
  'dist_jogador1': 0,
  'dist_jogador2': 19,
  'dist_jogador3': 14,
  'dist_jogador4': 24,
  'dist_powerup': 0,
  'funcao': 'passear_pelo_mapa',
  'mais_de_um_jogador_perto': 0,
  'neutro': 1,
  'oportunidade': 0,
  'perigo': 0,
  'player_com_powerup': 1,
  'powerup_existe': 0},
 {'bomba_existe': 0,
  'bomba_player': 0,
  'dist_bomba1': 0,
  'dist_bomba2': 0,
  'dist_bomba3': 0,
  'dist_bomba4': 0,
  'dist_jogador1': 0,
  'dist_jogador2': 20,
  'dist_jogador3': 17,
  'dist_jogador4': 16,
  'dist_powerup': 0,
  'funcao': 'passear_pelo_mapa',
  'mais_de_um_jogador_perto': 0,
  'neutro': 1,
  'oportunidade': 0,
  'perigo': 0,
  'player_com_powerup': 0,
  'powerup_existe': 0},
 {'bomba_existe': 0,
  'bomba_player': 0,
  'dist_bomba1': 0,
  'dist_bomba2': 0,
  'dist_bomba3': 0,
  'dist_bomba4': 0,
  'dist_jogador1': 0,
  'dist_jogador2': 16,
  'dist_jogador3': 16,
  'dist_jogador4': 16,
  'dist_powerup': 0,
  'funcao': 'passear_pelo_mapa',
  'mais_de_um_jogador_perto': 0,
  'neutro': 1,
  'oportunidade': 0,
  'perigo': 0,
  'player_com_powerup': 0,
  'powerup_existe': 0},
 {'bomba_existe': 0,
  'bomba_player': 0,
  'dist_bomba1': 0,
  'dist_bomba2': 0,
  'dist_bomba3': 0,
  'dist_bomba4': 0,
  'dist_jogador1': 0,
  'dist_jogador2': 24,
  'dist_jogador3': 19,
  'dist_jogador4': 24,
  'dist_powerup': 0,
  'funcao': 'passear_pelo_mapa',
  'mais_de_um_jogador_perto': 0,
  'neutro': 1,
  'oportunidade': 0,
  'perigo': 0,
  'player_com_powerup': 1,
  'powerup_existe': 0},
 {'bomba_existe': 0,
  'bomba_player': 0,
  'dist_bomba1': 0,
  'dist_bomba2': 0,
  'dist_bomba3': 0,
  'dist_bomba4': 0,
  'dist_jogador1': 0,
  'dist_jogador2': 14,
  'dist_jogador3': 17,
  'dist_jogador4': 13,
  'dist_powerup': 0,
  'funcao': 'passear_pelo_mapa',
  'mais_de_um_jogador_perto': 0,
  'neutro': 1,
  'oportunidade': 0,
  'perigo': 0,
  'player_com_powerup': 1,
  'powerup_existe': 0},
 {'bomba_existe': 0,
  'bomba_player': 0,
  'dist_bomba1': 0,
  'dist_bomba2': 0,
  'dist_bomba3': 0,
  'dist_bomba4': 0,
  'dist_jogador1': 0,
  'dist_jogador2': 17,
  'dist_jogador3': 21,
  'dist_jogador4': 13,
  'dist_powerup': 0,
  'funcao': 'passear_pelo_mapa',
  'mais_de_um_jogador_perto': 0,
  'neutro': 1,
  'oportunidade': 0,
  'perigo': 0,
  'player_com_powerup': 1,
  'powerup_existe': 0},
 {'bomba_existe': 0,
  'bomba_player': 0,
  'dist_bomba1': 0,
  'dist_bomba2': 0,
  'dist_bomba3': 0,
  'dist_bomba4': 0,
  'dist_jogador1': 0,
  'dist_jogador2': 18,
  'dist_jogador3': 15,
  'dist_jogador4': 21,
  'dist_powerup': 0,
  'funcao': 'passear_pelo_mapa',
  'mais_de_um_jogador_perto': 0,
  'neutro': 1,
  'oportunidade': 0,
  'perigo': 0,
  'player_com_powerup': 0,
  'powerup_existe': 0},
 {'bomba_existe': 0,
  'bomba_player': 0,
  'dist_bomba1': 0,
  'dist_bomba2': 0,
  'dist_bomba3': 0,
  'dist_bomba4': 0,
  'dist_jogador1': 0,
  'dist_jogador2': 15,
  'dist_jogador3': 16,
  'dist_jogador4': 17,
  'dist_powerup': 0,
  'funcao': 'passear_pelo_mapa',
  'mais_de_um_jogador_perto': 0,
  'neutro': 1,
  'oportunidade': 0,
  'perigo': 0,
  'player_com_powerup': 0,
  'powerup_existe': 0},
 {'bomba_existe': 0,
  'bomba_player': 0,
  'dist_bomba1': 0,
  'dist_bomba2': 0,
  'dist_bomba3': 0,
  'dist_bomba4': 0,
  'dist_jogador1': 0,
  'dist_jogador2': 14,
  'dist_jogador3': 13,
  'dist_jogador4': 21,
  'dist_powerup': 0,
  'funcao': 'passear_pelo_mapa',
  'mais_de_um_jogador_perto': 0,
  'neutro': 1,
  'oportunidade': 0,
  'perigo': 0,
  'player_com_powerup': 1,
  'powerup_existe': 0}
  ]
    
exemploDadoReal = [{'bomba_existe': 1,
  'bomba_player': 1,
  'dist_bomba1': 3,
  'dist_bomba2': 9,
  'dist_bomba3': 10,
  'dist_bomba4': 5,
  'dist_jogador1': 0,
  'dist_jogador2': 9,
  'dist_jogador3': 11,
  'dist_jogador4': 3,
  'dist_powerup': 2,
  'mais_de_um_jogador_perto': 0,
  'neutro': 0,
  'oportunidade': 0,
  'perigo': 1,
  'player_com_powerup': 0,
  'powerup_existe': 1}]
# dadosFiltrados = filtrarDadosTreinamento(dadosTreinamento, powerup_existe=0)
# pprint.pprint(dadosFiltrados)

# dataframeTreino = pd.DataFrame(dados_treinamento_fixos())
# dadoReal = pd.DataFrame(exemploDadoReal)
# result = arvorePredict(dadoReal, dataframeTreino)
# print(result)








def fugir():
    return 'cima'
def atacar_e_desviar():
    return 'bomba'
def pegar_powerUp():
    return 'baixo'


def passear_pelo_mapa(player, mapa, jogadores, bombas):
    pos = player["pos"]
    x, y = pos
    largura = len(mapa[0])
    altura = len(mapa)

    # -------------------------------------------------------------
    # Funções auxiliares
    def pos_valida(px, py):
        return 0 <= px < largura and 0 <= py < altura and mapa[py][px] == 0

    def mover_para(origem, destino):
        ox, oy = origem
        dx, dy = destino
        if dx > ox: return "direita"
        if dx < ox: return "esquerda"
        if dy > oy: return "baixo"
        if dy < oy: return "cima"
        return "parado"

    # -------------------------------------------------------------
    # 1️⃣ Calcular zonas de perigo com base nas bombas
    zonas_perigo = set()
    for bomba in bombas:
        bx, by = bomba["pos"]
        alcance = bomba.get("alcance", player["bomba_nivel"] + 2)
        zonas_perigo.add((bx, by))
        for dx, dy in [(1,0),(-1,0),(0,1),(0,-1)]:
            for i in range(1, alcance+1):
                nx, ny = bx + dx*i, by + dy*i
                if not (0 <= nx < largura and 0 <= ny < altura):
                    break
                if mapa[ny][nx] == 2:  # parede indestrutível bloqueia explosão
                    break
                zonas_perigo.add((nx, ny))
                if mapa[ny][nx] == 1:  # para em bloco quebrável
                    break

    # -------------------------------------------------------------
    # 2️⃣ Se estiver em perigo → fugir
    if (x, y) in zonas_perigo:
        destino_seguro = achar_posicao_segura(mapa, zonas_perigo, (x, y))
        if destino_seguro:
            return mover_para((x, y), destino_seguro)
        else:
            return "parado"

    # -------------------------------------------------------------
    # 3️⃣ Se tiver bloco quebrável adjacente → soltar bomba
    for dx, dy in [(0, -1), (0, 1), (-1, 0), (1, 0)]:
        nx, ny = x + dx, y + dy
        if 0 <= nx < largura and 0 <= ny < altura:
            if mapa[ny][nx] == 1 and player["bombas_ativas"] < player["max_bombas"]:
                return "bomba"

    # -------------------------------------------------------------
    # 4️⃣ Procurar bloco quebrável mais próximo (via BFS)
    alvo = achar_bloco_quebravel_mais_proximo(mapa, (x, y), zonas_perigo)
    if alvo:
        return mover_para((x, y), alvo)

    # -------------------------------------------------------------
    # 5️⃣ Se não houver blocos → andar aleatoriamente em zona segura
    direcoes = [("cima", (0, -1)), ("baixo", (0, 1)), ("esquerda", (-1, 0)), ("direita", (1, 0))]
    random.shuffle(direcoes)
    for nome, (dx, dy) in direcoes:
        nx, ny = x + dx, y + dy
        if pos_valida(nx, ny) and (nx, ny) not in zonas_perigo:
            return nome

    return "parado"


def achar_posicao_segura(mapa, zonas_perigo, origem):
    """Busca a posição segura mais próxima (fora da área de explosão)."""
    largura = len(mapa[0])
    altura = len(mapa)
    fila = deque([origem])
    visitados = {origem}
    pais = {origem: None}

    while fila:
        x, y = fila.popleft()
        if (x, y) not in zonas_perigo and mapa[y][x] == 0:
            # Achou posição segura — retorna o primeiro passo
            while pais[(x, y)] != origem and pais[(x, y)] is not None:
                x, y = pais[(x, y)]
            return (x, y)
        for dx, dy in [(0,1),(0,-1),(1,0),(-1,0)]:
            nx, ny = x + dx, y + dy
            if 0 <= nx < largura and 0 <= ny < altura and (nx, ny) not in visitados:
                if mapa[ny][nx] == 0:
                    visitados.add((nx, ny))
                    pais[(nx, ny)] = (x, y)
                    fila.append((nx, ny))
    return None


def achar_bloco_quebravel_mais_proximo(mapa, origem, zonas_perigo):
    """Procura o bloco quebrável mais próximo e retorna a primeira direção pra chegar até ele."""
    largura = len(mapa[0])
    altura = len(mapa)
    fila = deque([origem])
    visitados = {origem}
    pais = {origem: None}

    while fila:
        x, y = fila.popleft()
        # se há bloco quebrável adjacente, encontramos o destino final
        for dx, dy in [(1,0),(-1,0),(0,1),(0,-1)]:
            nx, ny = x + dx, y + dy
            if 0 <= nx < largura and 0 <= ny < altura:
                if mapa[ny][nx] == 1 and (x, y) not in zonas_perigo:
                    # sobe até o primeiro passo
                    while pais[(x, y)] != origem and pais[(x, y)] is not None:
                        x, y = pais[(x, y)]
                    return (x, y)
        # expandir busca
        for dx, dy in [(1,0),(-1,0),(0,1),(0,-1)]:
            nx, ny = x + dx, y + dy
            if 0 <= nx < largura and 0 <= ny < altura and (nx, ny) not in visitados:
                if mapa[ny][nx] == 0 and (nx, ny) not in zonas_perigo:
                    visitados.add((nx, ny))
                    pais[(nx, ny)] = (x, y)
                    fila.append((nx, ny))
    return None


def extrair_informacoes(player, mapa, jogadores, bombas):
    """
    Extrai informações do estado atual do jogo para uso em IA.
    Retorna um dicionário com posições e status relevantes.
    """

    info = {
        "player": {
    "id": getattr(player, "id", 0),
    "pos": (player.grid_x, player.grid_y),
    "ativo": player.ativo,
    "bomba_nivel": player.bomba_nivel,
    "max_bombas": player.max_bombas,
    "bombas_ativas": len(player.bombas)
    },
        "jogadores": [],
        "bombas": [],
        "powerups": [],
        "tem_bombas": False,
        "tem_powerups": False
    }

    # Jogadores
    for j in jogadores:
        info["jogadores"].append({
            "id": jogadores.index(j),
            "pos": (j.grid_x, j.grid_y),
            "ativo": j.ativo,
            "time": j.time
        })

    # Bombas
    for b in bombas:
        info["bombas"].append({
        "pos": (b.x, b.y),
        "nivel": b.nivel,
        "explodida": b.explodida,
        "tempo_explosao": b.tempo_explosao,
        "ativo": not b.explodida,  # ativa enquanto não explodir
        "owner_id": getattr(b, "owner_id", None)  # se existir, adiciona o dono
    })
    info["tem_bombas"] = len(info["bombas"]) > 0

    # PowerUps
    for y, linha in enumerate(mapa):
        for x, val in enumerate(linha):
            if val in [3, 4]:  # 3 = bomba, 4 = fogo
                info["powerups"].append({
                    "pos": (x, y),
                    "tipo": "bomba" if val == 3 else "fogo"
                })
    info["tem_powerups"] = len(info["powerups"]) > 0

    return info





def transformar_dados(player, jogadores, bombas, powerups, distancia_manhattan):
    # --- Inicialização do dicionário base ---
    dados = {
        'bomba_existe': 0,
        'bomba_player': 0,
        'dist_bomba1': 0,
        'dist_bomba2': 0,
        'dist_bomba3': 0,
        'dist_bomba4': 0,
        'dist_jogador1': 0,
        'dist_jogador2': 0,
        'dist_jogador3': 0,
        'dist_jogador4': 0,
        'dist_powerup': 0,
        'mais_de_um_jogador_perto': 0,
        'neutro': 0,
        'oportunidade': 0,
        'perigo': 0,
        'player_com_powerup': 0,
        'powerup_existe': 0
    }

    px, py = player['pos']

    # --- Distâncias dos jogadores ---
    distancias_jogadores = []
    for i, j in enumerate(jogadores[:4], start=1):
        if j['ativo'] and j['pos'] is not None:
            d = distancia_manhattan(px, py, *j['pos'])
        else:
            d = 99  # valor padrão se não houver jogador
        dados[f'dist_jogador{i}'] = d
        distancias_jogadores.append(d)

    # --- Distâncias das bombas ---
    distancias_bombas = []
    for i, b in enumerate(bombas[:4], start=1):
        if b['ativo'] and b['pos'] is not None:
            d = distancia_manhattan(px, py, *b['pos'])
            dados[f'dist_bomba{i}'] = d
            distancias_bombas.append(d)
            dados['bomba_existe'] = 1
            if b.get('owner_id') == player['id']:  # bomba do player atual
                dados['bomba_player'] = 1
        else:
            dados[f'dist_bomba{i}'] = 99

    # --- PowerUp ---
    if len(powerups) > 0:
        dados['powerup_existe'] = 1
        dist_p = distancia_manhattan(px, py, *powerups[0]['pos'])
        dados['dist_powerup'] = dist_p
    else:
        dados['dist_powerup'] = 99

    # --- Lógica de perigo, oportunidade e neutro ---
    jogadores_perto = [d for d in distancias_jogadores if d < 5]

    if len(jogadores_perto) == 1:
        dados['perigo'] = 1
    elif len(jogadores_perto) > 1:
        dados['perigo'] = 1
        dados['mais_de_um_jogador_perto'] = 1
    elif dados['powerup_existe'] == 1:
        dados['oportunidade'] = 1
    else:
        dados['neutro'] = 1

    # --- Powerup do player ---
    if player.get('tem_powerup', False):
        dados['player_com_powerup'] = 1

    return dados




def decidir_acao(player, mapa, jogadores, bombas, tempo_restante, pontos, hud_info, self_state):
    # estadoDeJogo = extrair_informacoes(player, mapa, jogadores, bombas)
    # print('\n\n estado de jogo \n\n')
    # print(estadoDeJogo)
    estado = extrair_informacoes(player, mapa, jogadores, bombas)
    print('\n\n Extrair Informações\n')
    print(estado)
    # Transforma o estado em dados estruturados para IA
    exemploDadoReal = transformar_dados(
        estado["player"],
        estado["jogadores"],
        estado["bombas"],
        estado["powerups"],
        distancia_manhattan
    )

    print("\n--- Estado Transformado ---")
    print(exemploDadoReal)
    dataframeTreino = pd.DataFrame(dados_treinamento_fixos())
    dadoReal = pd.DataFrame([exemploDadoReal])

    result = arvorePredict(dadoReal, dataframeTreino)
    acao = result[0]

    if acao == 'atacar_e_desviar':
        # return atacar_e_desviar()
        return passear_pelo_mapa(estado["player"], mapa, estado["jogadores"], estado["bombas"])
    elif acao == 'fugir':
        # return fugir()
        return passear_pelo_mapa(estado["player"], mapa, estado["jogadores"], estado["bombas"])
    elif acao == 'pegar_powerUp':
        # return pegar_powerUp()
        return passear_pelo_mapa(estado["player"], mapa, estado["jogadores"], estado["bombas"])
    elif acao == 'passear_pelo_mapa':
        # return passear_pelo_mapa()
        return passear_pelo_mapa(estado["player"], mapa, estado["jogadores"], estado["bombas"])
    log_estado_jogo(player, jogadores, bombas, mapa)
    
